Princeton-CDH/geniza

.gitignore, README.md, requirements.txt, scripts/index.py, scripts/local_settings.py.sample, scripts/server.py, scripts/tei_transcriptions.py, scripts/templates/results.html, solr_conf/conf/solrconfig.xml
Adds a new flask command to do basic parsing of TEI transcriptions that creates a json file with extracted information, updates indexing to include transcription data when available, adds transcription to search fields, and adds highlighting of matches in transcription text.
To generate transcription data file:
1. Download a local copy of the TEI/XML data
2. Configure the path in flask local settings as **XML_TRANSCRIPTIONS_DIR**
3. Run the command: `flask transcriptions`
Once you have the transcription data file, you can run `flask index` to index metadata + transcription text.
Requires a solr config change to search on transcription text.
=> Basic tei transcription conversion & search

solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
ref #9 
I copied the new solr config in, restarted solr, and reindexed and that was sufficient for this change to take effect.
=> Configure unicode folding filter for general text #9

scripts/server.py, scripts/templates/base.html, scripts/templates/clusters.html, scripts/templates/results.html
=> List of tag-pair clusters with document counts

geniza/__init__.py, geniza/settings/components/base.py, geniza/urls.py
As @thatbudakguy pointed out somewhere, we need a python package version for the site.
Copied this code from other projects so it doesn't really need review, but thought a quick PR wouldn't hurt.
I decided to set the version as 0.3 since we've already created two prototypes, but that's kind of arbitrary. Not sure how much it matters. 😄
=> Define application version and make available via context processor

geniza/corpus/management/commands/data_import.py
@rlskoeser Just some quick things to talk about 
* I hamfisted a way to just get the latest 500 csvrows. Could we create a command-line flag like `--dev` or `--full`?
* There was quite a facepalm typo in line 239
* We are making a comparison to `doc.shelfmark` while adding shelfmarks. Can you confirm that this will be a problem?
=> Fix error in joins import

geniza/corpus/management/commands/import_data.py, geniza/corpus/tests/test_import_data.py
- revise to map languages to Language+Script based on display name or newly added spreadsheet_name (needed for a few cases)
- case-insensitive comparison to handle variation in the spreadsheet
=> Revise document language import

geniza/footnotes/admin.py, geniza/footnotes/tests/test_footnote_admin.py
Two concerns, please tell me if they should be addressed:
1. I haven't written a test for this, should I?
2. I've placed this function in the admin, not on `Source` because it seems like the application of this method is only useful in the admin. Is that accurate?
=> Add footnote_count function to SourceAdmin

geniza/corpus/admin.py, geniza/corpus/tests/test_corpus_admin.py
Refactored the admin documents csv download to make it more performant; added some more prefetching, dropped the footnotes. I'll add a comment with my timing testing as I refactored it
=> optimize admin documents csv

geniza/corpus/admin.py, geniza/footnotes/admin.py, geniza/footnotes/templates/admin/footnotes/source/change_list.html, geniza/footnotes/tests/test_footnote_admin.py
adapted from the documents admin csv download
=> Add admin csv export for source data

geniza/templates/base.html, geniza/templates/nav.html, sitemedia/css/style.css
adds a basic main navigation similar to gissoo's design. no styles for mobile yet. no tests, since i think this snippet may change a fair bit.
=> Basic main navigation template

geniza/corpus/forms.py, geniza/corpus/templates/corpus/document_detail.html, geniza/locale/ar/LC_MESSAGES/django.po, geniza/locale/en/LC_MESSAGES/django.po, geniza/locale/he/LC_MESSAGES/django.po
Was looking at the localization and noticed that we missed adding it to the UI text in the search form, and I think also had not regenerated the message files in a while.
=> Localize search form and regenerate messages

geniza/corpus/templates/corpus/document_list.html
small change to humanize the total results on the document list, so it's more readable
=> Add intcomma to search results total

DEPLOYNOTES.md, geniza/corpus/management/commands/sync_transcriptions.py, geniza/corpus/tei_transcriptions.py, geniza/corpus/tests/fixtures/968.xml, geniza/corpus/tests/test_tei_transcription.py, geniza/footnotes/models.py, geniza/footnotes/templates/footnotes/transcription.html, geniza/footnotes/tests/test_footnote_admin.py, geniza/footnotes/tests/test_footnote_models.py, geniza/settings/components/base.py, requirements/prod.txt, sitemedia/css/admin-local.css
Preliminary work on a new manage command to sync TEI transcription content to content associated with footnotes that we can use for the MVP site. There are still a number of questions that need to be resolved, but I thought it would be helpful to get eyes on what I've drafted so far.
I haven't written any unit tests yet, and I'm not sure how much I want to write — this is intended to be an interim solution and I'm not sure yet if we'll use any of this code for the "real" solution; possibly none.
=> Manage command to sync TEI transcriptions to html content in footnotes (WIP)

geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py
... not for solr's default first ten results
=> Get solr highlighting for *paginated* results

geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/templates/corpus/snippets/document_tabs.html, geniza/corpus/tests/test_corpus_templates.py, sitemedia/scss/base/_typography.scss, sitemedia/scss/components/_docheader.scss, sitemedia/scss/components/_footnote.scss, sitemedia/scss/components/_results.scss, sitemedia/scss/components/_tabs.scss, sitemedia/scss/pages/_document.scss
- Per https://github.com/Princeton-CDH/geniza/issues/396#issuecomment-995270444:
- Adjusts type sizes, styles as specified
- Fixes issue with document tabs not spacing properly with 0 external links
=> #396 - Type style revisions

sitemedia/scss/base/_colors.scss, sitemedia/scss/base/_global.scss, sitemedia/scss/base/_typography.scss, sitemedia/scss/components/_footnote.scss, sitemedia/scss/components/_navigation.scss, sitemedia/scss/components/_pagination.scss, sitemedia/scss/components/_results.scss, sitemedia/scss/components/_searchform.scss, sitemedia/scss/pages/_document.scss
Per #402, adds all the new colors in and removes unused old colors.
Note that this does not mean all components have correct colors yet—in fact, many do not. But this will at least allow for progress on the individual component issues with a standardized set of colors.
=> #402 - Replace all colors

geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/tests/test_corpus_templates.py
Example of a multi-shelfmark doc: PGPID 444
=> 460 show shelfmarks in doc detail

DEPLOYNOTES.md, geniza/corpus/models.py, geniza/corpus/solr_queryset.py, geniza/corpus/tests/test_corpus_models.py, geniza/corpus/tests/test_corpus_solrqueryset.py, solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
=> Index tags as lowercase for case-insensitive match

geniza/corpus/templates/corpus/snippets/pagination.html, geniza/corpus/tests/test_corpus_templates.py, sitemedia/scss/components/_pagination.scss
[Latest Percy build](https://percy.io/2cf28a24/geniza/builds/15062034)
In scope:
- Pagination controls, mobile and desktop, light and dark modes
- Per #451:
- Implements new pagination designs on mobile and desktop
=> #451 - Implement new pagination designs

sitemedia/scss/base/_fonts.scss
- Implements Arial at 83% for Greta Sans fallback fonts
=> Implement fallback fonts

DEPLOYNOTES.md, geniza/templates/base.html, sitemedia/scss/base/_fonts.scss
Pretty simple change: just adds the fonts to the fallback flow, making the new ones the first in line to render; and preloads them in `base.html`.
=> Add new Latin fonts, use old for Hebrew fallback

geniza/corpus/templates/corpus/snippets/document_transcription.html
=> Expand all transcriptions on doc detail by default

geniza/corpus/templates/admin/corpus/document/change_form.html, sitemedia/css/admin-local.css
=> #608 - Horizontal display for multiple transcriptions in admin

sitemedia/css/admin-local.css
=> Allow overflow for footnote admin source inline

DEPLOYNOTES.md, geniza/context_processors.py, geniza/templates/base.html, geniza/templates/snippets/analytics.html
=> Add configuration & template for google analytics

geniza/corpus/templates/corpus/document_scholarship.html
=> Remove "unpublished" label from frontend

geniza/context_processors.py, geniza/templates/footer.html, sitemedia/scss/components/_footer.scss
(Not explicitly designed; added in a location that looked reasonable and adapted existing styles)
=> Add software version to footer

geniza/corpus/models.py
handle model-translated document description field when merging — check and combine content from descriptions for all supported languages
=> Update document merge for translatable description

sitemedia/scss/pages/_content.scss
Fixes issue with image max-width and `:not` rules
=> Fix and simplify CSS for images in content pages

sitemedia/scss/components/_results.scss
=> Space multiple images closer together on mobile

geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/tests/test_corpus_templates.py, geniza/locale/ar/LC_MESSAGES/django.po, geniza/locale/en/LC_MESSAGES/django.po, geniza/locale/he/LC_MESSAGES/django.po, sitemedia/scss/pages/_document.scss
Also moves secondary metadata below description
ref #715
=> Display languages on public document details

.pre-commit-config.yaml, geniza/common/management/commands/visual_tests.py, sitemedia/scss/components/_searchform.scss
- Fixes Percy bug by increasing the z-index for the mobile filter modal in the search form
=> Increase z-index for filter modal on mobile

geniza/corpus/forms.py, geniza/corpus/models.py, geniza/corpus/solr_queryset.py, geniza/corpus/templates/corpus/document_list.html, geniza/corpus/tests/test_corpus_models.py, geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py
- Allows the user to filter documents by the presence of IIIF images
=> Add has_image filter to document search (#691)

sitemedia/scss/base/_typography.scss, sitemedia/scss/pages/_error.scss
[percy build](https://percy.io/2cf28a24/geniza/builds/17369217/)
In scope:
- Per #751:
- Implements revised styles for H1, H2, and H3 headers
=> Implement revised header styles (#751)

sitemedia/css/admin-local.css, sitemedia/scss/components/_iiif.scss
- Per #708:
- Allows wrapping of long lines in admin
- Fixes an issue with images not displaying on mobile
=> Improve transcription display on admin (#708)

geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/tests/test_corpus_templates.py
per feedback from Alan about "fragment" not being accurate in all cases
=> Relabel related documents fragments -> shelfmark

sitemedia/scss/components/_searchform.scss
- Per #753:
- Adjusts styles for search form in RTL layout to match designs
=> RTL revisions for search form (#753)

sitemedia/scss/components/_results.scss, sitemedia/scss/components/_tag.scss
- Per #769:
- Implements RTL tweaks for individual search results (and their tags) per designs
=> Implement RTL revisions for search results (#769)

geniza/corpus/management/commands/add_fragment_urls.py
=> Ignore case when finding fragments by shelfmark

geniza/corpus/admin.py, geniza/corpus/tests/test_corpus_admin.py
=> Optimize Language+Script autocomplete queryset

geniza/corpus/tests/test_corpus_views.py, solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
=> Configure bigram indexing for shelfmarks

geniza/corpus/models.py, geniza/corpus/solr_queryset.py, geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/templates/corpus/snippets/document_result.html, geniza/corpus/templates/corpus/snippets/document_transcription.html, geniza/corpus/templatetags/corpus_extras.py, geniza/corpus/tests/test_corpus_models.py, geniza/corpus/tests/test_corpus_solrqueryset.py, geniza/corpus/tests/test_corpus_templates.py, geniza/corpus/tests/test_corpus_templatetags.py, geniza/corpus/views.py, geniza/footnotes/models.py, geniza/footnotes/templates/footnotes/transcription.html, geniza/footnotes/tests/test_footnote_models.py, geniza/urls.py, requirements/prod.txt, sitemedia/scss/components/_transcription.scss, sitemedia/scss/pages/_document.scss, solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
index transcription as html instead of plain text
still needs tests and styling revisions
=> Index transcription as html

geniza/corpus/management/commands/tei_to_annotation.py, geniza/footnotes/templates/admin/footnotes/footnote/change_form.html
- normalize unicode
- report on unmigrated footnotes
- fix transcription display in footnote admin
=> Tei to annotation revisions

geniza/locale/ar/LC_MESSAGES/django.po, geniza/locale/en/LC_MESSAGES/django.po, geniza/locale/he/LC_MESSAGES/django.po, geniza/templates/footer.html
=> Use social media usernames in footer to avoid duplicate link text

geniza/corpus/migrations/0035_document_image_order_override.py, geniza/corpus/models.py
=> Make image order override optional in django admin

geniza/corpus/management/commands/tei_to_annotation.py, geniza/corpus/models.py, geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/templates/corpus/snippets/document_transcription.html, geniza/corpus/tests/test_corpus_models.py, geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py
partial refactor; updates `Document.iiif_images` to return a dict instead of a list; in reference to PR #1056
only partially tested, haven't updated all the unit tests; may well be other places that we need to update
=> Revise Document.iiif_images to return dict instead of list

package-lock.json, package.json
- Per #1057:
- Bump tahqiq commit hash to implement new drop zone behavior
See also https://github.com/Princeton-CDH/annotorious-tahqiq/pull/17
=> Bump tahqiq commit hash for dropzone (#1057)

geniza/corpus/templates/corpus/document_transcribe.html, geniza/corpus/templates/corpus/snippets/document_transcription.html, package-lock.json, package.json
- Per #1131:
- Add help text from issue comment
- Per #1129, #1148:
- Bump tahqiq commit hash to include fixes from https://github.com/Princeton-CDH/annotorious-tahqiq/pull/21
- Prevent turbo from taking control of the "return to document detail page" link
=> Transcription editor miscellaneous tweaks (#1129, #1131, #1148)

geniza/corpus/templates/corpus/document_detail.html, package-lock.json, package.json
- Bump tahqiq commit hash for fix to reload on creating annotations
- Remove unused transcription download code
=> Transcription editor fix (reload on create annotation)

geniza/corpus/admin.py, geniza/footnotes/admin.py, sitemedia/css/admin-local.css
=> Configure Hebrew and Arabic model translate inputs to be RTL

geniza/corpus/management/commands/sync_annotation_export.py, geniza/corpus/tests/test_sync_annotation_export.py
=> Include PGPID in git commit message for incremental annotation exports

sitemedia/js/controllers/iiif_controller.js
- Per #1191 
- Disable OSD navigator for placeholder images
=> Disable navigator for placeholder images (#1191)

geniza/common/metadata_export.py, geniza/common/tests.py, geniza/corpus/admin.py, geniza/corpus/metadata_export.py, geniza/corpus/models.py, geniza/corpus/tests/test_corpus_models.py
This is a PR response to issue #953.
=> Exports include transcription (Y/N) and translation (Y/N)

geniza/common/metadata_export.py, geniza/corpus/metadata_export.py, geniza/corpus/tests/test_metadata_export.py
This is to fix https://github.com/Princeton-CDH/geniza/issues/1097.
=> PublicDocumentExporter

geniza/corpus/metadata_export.py, geniza/corpus/tests/test_corpus_admin.py, geniza/footnotes/admin.py, geniza/footnotes/metadata_export.py, geniza/footnotes/models.py, geniza/footnotes/tests/test_footnote_admin.py, geniza/footnotes/tests/test_footnote_metadata_export.py
ref #1100 #278
rewrites the existing source tabular export to use the new metadata export code
=> Rewrite footnotes source tabular export to use new exporter class

geniza/corpus/admin.py, geniza/corpus/metadata_export.py, geniza/corpus/templates/admin/corpus/fragment/change_list.html, geniza/corpus/templates/admin/corpus/fragment/change_list_object_tools.html, geniza/corpus/tests/test_corpus_admin.py, geniza/corpus/tests/test_metadata_export.py
new fragment metadata export, with admin variant; wired into fragment admin, unit tested
=> Implement fragment export

geniza/corpus/management/commands/export_metadata.py, geniza/corpus/metadata_export.py, geniza/corpus/tests/test_metadata_export.py, geniza/footnotes/metadata_export.py, geniza/footnotes/tests/test_footnote_metadata_export.py
=> Fixing bug in admin vs public exporter

solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
- for #1254 : add unicode folding to description bigram text field
- for #1256 : adjust phrase field boosting
=> address search regressions

geniza/annotations/tests/test_annotations_views.py, geniza/annotations/views.py
=> revise anotation search view for annotation model changes

geniza/annotations/models.py, geniza/annotations/tests/test_annotations_models.py, geniza/annotations/tests/test_annotations_views.py, geniza/annotations/views.py
part of #1238
should be reviewed after #1267
=> revise annotation model serialization to JSON for annotation model changes

geniza/corpus/solr_queryset.py, geniza/corpus/tests/test_corpus_solrqueryset.py
=> Additional search term cleanup for shelfmark that looks like boolean

geniza/corpus/admin.py, geniza/corpus/templates/admin/corpus/document/object_history.html, geniza/corpus/templates/admin/corpus/document/snippets/change_history_table.html, geniza/corpus/tests/test_corpus_admin.py, sitemedia/css/admin-local.css
- Per  #1260:
- Add log entries for related footnotes and annotations to document history view/template
=> Transcription logging (#1260)

.github/workflows/lighthouse.yml, .github/workflows/unit_tests.yml, .github/workflows/visual_tests.yml, DEPLOYNOTES.md, geniza/corpus/solr_queryset.py, geniza/corpus/tests/test_corpus_solrqueryset.py, geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py, solr_conf/conf/managed-schema, solr_conf/conf/solrconfig.xml
Reverts Princeton-CDH/geniza#1322 due to accidentally committed feature branch commits.
Note that this may cause problems when we try to reintroduce those commits, we may need to cherry pick them to get them back, per [this StackOverflow answer](https://stackoverflow.com/a/7101376).
=> Revert "Update github actions to postgres 13"

sitemedia/scss/components/_transcription.scss
=> Give lis consistent line height for alignment

geniza/corpus/metadata_export.py, geniza/corpus/tests/test_metadata_export.py
per https://github.com/Princeton-CDH/geniza/issues/1399#issuecomment-1699564393
=> Rename dating export columns for clarity (#1399)

geniza/corpus/admin.py, geniza/corpus/tests/test_corpus_admin.py
=> Use built-in autocomplete for documents inline

DEPLOYNOTES.md, geniza/admin.py, geniza/entities/templates/admin/entities/place/change_form.html, geniza/settings/local_settings.py.sample, package-lock.json, package.json, sitemedia/js/admin.js
also mapbox --> maplibre because mapbox is not FOSS anymore
=> Add confirmation before saving place without coordinates (#1478)

geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/tests/test_corpus_templates.py
=> Display inferred date on document details when set (#875)

geniza/corpus/models.py, geniza/entities/models.py, geniza/entities/templates/entities/person_detail.html, geniza/entities/tests/test_entities_models.py, sitemedia/scss/pages/_person.scss
Also make permalink code reusable from Document, since it's identical
=> Include citation and permalink in Person Detail page (#1569)

geniza/entities/templates/entities/person_list.html, geniza/entities/tests/test_entities_views.py, geniza/entities/views.py, sitemedia/js/controllers/search_controller.js, sitemedia/scss/base/_colors.scss, sitemedia/scss/components/_peopleform.scss
Per #1606:
- Add "chips" above the person results for each applied filter, as a button to unapply each
- Add a "clear all" button
=> Add chip buttons to unapply individual filters (#1606)

geniza/corpus/templates/corpus/widgets/yearrangewidget.html, geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py, geniza/entities/forms.py, geniza/entities/templates/entities/person_list.html, geniza/entities/tests/test_entities_views.py, geniza/entities/views.py, sitemedia/js/controllers/search_controller.js, sitemedia/scss/components/_peopleform.scss, sitemedia/scss/components/_searchform.scss
Per #1597:
- Make solr full date range logic reusable (`SolrDateRangeMixin`)
- Add date range filter to person list view and form
=> Add date range filter to person list page (#1597)

sitemedia/js/admin.js, sitemedia/js/controllers/map_controller.js
Fixes a bug that caused Arabic script to appear backwards on maps.
=> Implement maplibre RTL text plugin

geniza/corpus/management/commands/export_metadata.py, geniza/corpus/tests/test_metadata_export.py, geniza/entities/admin.py, geniza/entities/metadata_export.py, geniza/entities/templates/admin/entities/person/change_list.html, geniza/entities/tests/test_entities_admin.py, geniza/entities/tests/test_entities_metadata_export.py
Adapted from document export with changes specific to requested `Person` fields and data types.
=> People metadata export, public (#1633) and admin (#1641)

geniza/entities/admin.py, geniza/entities/metadata_export.py, geniza/entities/templates/admin/entities/place/change_form.html, geniza/entities/tests/test_entities_admin.py, geniza/entities/tests/test_entities_metadata_export.py
Per #1641:
- Create a new exporter `PlaceRelationsExporter` that creates a csv of objects related to a place
- Adapt from `PersonRelationsExporter`
- Extract as much shared code as possible with `PersonRelationsExporter` into mixin
- Make this new exporter available from the admin change form
=> Create place relations CSV admin export (#1641)

geniza/corpus/models.py, geniza/corpus/templates/corpus/document_detail.html, geniza/corpus/tests/test_corpus_models.py, geniza/locale/ar/LC_MESSAGES/django.po, geniza/locale/en/LC_MESSAGES/django.po, geniza/locale/he/LC_MESSAGES/django.po
Per #1662:
- Add URL field to collection model
- List and link to collections on document detail pages
=> Add collection information to doc detail page (#1662)

sitemedia/css/admin-local.css
Additional styling for the admin UI to unhide the line numbers and fix some buttons' padding
=> Unhide transcription line numbers on admin (#1672)

sitemedia/js/controllers/iiif_controller.js
Per #1673:
- Set rotation clockwise due to new rotation UI
- Other tweaks that help make the new rotation control function as expected
=> Set rotation controls clockwise, improve behavior (#1673)

geniza/entities/admin.py, geniza/entities/forms.py, geniza/entities/models.py, geniza/entities/templates/admin/entities/persondocumentrelationtype/merge.html, geniza/entities/templates/entities/snippets/persondocumentrelationtype_option_label.html, geniza/entities/tests/test_entities_forms.py, geniza/entities/tests/test_entities_models.py, geniza/entities/tests/test_entities_views.py, geniza/entities/views.py, sitemedia/css/admin-local.css
Per #1709:
- Allow admin users to merge Person-Document Relation Types
=> Person-Document Relation Type merge (#1709)

geniza/common/utils.py, geniza/corpus/templates/corpus/document_scholarship.html, geniza/corpus/templates/corpus/snippets/document_transcription.html, geniza/corpus/templatetags/corpus_extras.py, geniza/corpus/tests/test_corpus_templates.py, geniza/corpus/tests/test_corpus_templatetags.py, geniza/corpus/tests/test_corpus_views.py, geniza/corpus/views.py, geniza/footnotes/conftest.py, geniza/footnotes/models.py, geniza/footnotes/tests/test_footnote_models.py
Per #1502:
- Handle unpublished scholarship citation in transcription/translation viewer
- Handle grouped unpublished scholarship citations on bibliography pages
- Handle citations for Goitein unpublished records and index cards with hard-coded date range and formatting
=> Handle unpublished scholarship, Goitein index cards in citations (#1502)

geniza/corpus/management/commands/escr_alto_to_annotation.py, geniza/corpus/tests/test_escr_alto_to_annotation.py
Per #1770:
- Allow newly-ingested annotations to appear as the first blocks on a canvas, so that the Weiss errors can be gracefully corrected
- (Weiss error was that only the final page of multi-page OCR was getting attached as annotation to a canvas)
=> eScr ingest revisions for Weiss (#1770)

geniza/entities/forms.py
Per #1497:
- add the included help text to person-person relationship inline
=> Update person-person relationship helptext (#1497)

geniza/corpus/templates/corpus/snippets/document_transcription.html, sitemedia/js/controllers/iiif_controller.js, sitemedia/scss/components/_transcription.scss
Per #1312:
- Allow editing the IIIF viewer rotation degrees by clicking and typing (numeric input)
=> Allow rotation by typing degrees (#1312)

sitemedia/js/admin.js, sitemedia/js/controllers/map_controller.js, sitemedia/scss/pages/_places.scss
**Associated Issue(s):** #1782
- Add metric and imperial scales to all maps
=> Add scale to maps (#1782)
