requirements.txt
scripts/index.py
scripts/server.py
scripts/templates/cluster_result.html
scripts/templates/clusters.html

Expands on first topic cluster list — clusters are now clickable, and when you select one you get a list of the documents in that cluster, grouped by distinct sets of tags. 
ref #23

browse documents by topic cluster

---

scripts/index.py
scripts/local_settings.py.sample
scripts/tei_transcriptions.py

Small change to make data dir configurable instead of assuming it's local to the deploy, so we can preserve data files across deploys in qa/prod.

Make data dir configurable so it can be kept external to deploys

---

.gitignore
scripts/index.py
scripts/local_settings.py.sample
scripts/server.py
scripts/tei_transcriptions.py
scripts/templates/base.html
scripts/templates/iiif_viewer.html

This is a basic, first-pass conversion of TEI transcriptions to IIIF annotations to help us all understand what transcriptions as annotations might look like and how they would work, and to get a better sense of how the current transcription data needs to be broken up.
Changes include:
- tweak the index script to fix the IIIF urls for Cambridge (I think they changed something recently on their end, because this was working previously)
- new script to generate iiif annotation lists for documents that have both IIIF and transcriptions (currently Cambridge only); for now, all annotations are added to the first image in the manifest and are attached to the whole page; multiple annotations are added when there are multiple blocks in the TEI document (as indicated by labels for new sections)
- …

Basic conversion of TEI transcriptions to IIIIF annotations

---

geniza/corpus/admin.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_admin.py
geniza/corpus/tests/test_corpus_models.py
geniza/templates/admin/corpus/fragment/change_form.html

- shift `Document` language/probable language validation to admin `DocumentForm` because model `clean` method is insufficient
- configure language and probable languages as autocomplete instead of horizontal filter, to decrease space
- add validation to disallow unknown set as probable language, since admin autocomplete does not honor `limit_choices_to`
- use `EmptyFieldListFilter` instead of `BooleanFieldListFilter` for text field filters (multifragment & url)
- use https to load universalviewer script

Revise document/fragment admin

---

geniza/corpus/admin.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_admin.py
geniza/corpus/tests/test_corpus_models.py

Customize this model's save_model function and then execute the existing admin.ModelAdmin save_model function. Borrows from existing the `save_as` functionality.
**Questions**
* I can't grab the original document object from the save_as request, any ideas? (`obj` is the new object, its pk is None)
* How would I go about testing this?

Add save_as feature to document model

---

geniza/corpus/management/commands/import_data.py
geniza/corpus/tests/test_import_data.py

Realized there was a way to preserve the actual information entered in the spreadsheet so that it could be displayed for #112 – planning on adding some logic for that one to display the actual date entered (e.g. "January 1996") if it's present in the log entry, otherwise use the actual date of the log entry (for changes made after the spreadsheet). lmk if that doesn't make sense.

Preserve spreadsheet input dates via log entry change messages

---

geniza/corpus/admin.py
geniza/corpus/models.py
geniza/corpus/templates/admin/corpus/document/change_form.html
geniza/corpus/templates/admin/corpus/document/log_entry.html
geniza/corpus/templates/admin/corpus/document/rev_log_entry.html
geniza/corpus/tests/test_corpus_admin.py
sitemedia/css/admin-local.css

- Adds new admin templates for displaying data after fields
- Adds convenience field to Document to get its log entries
- Adds first/last log entries to admin context with legacy dates
See #112
no tests yet; opening draft to check the approach – it seems to be working for me locally

Add first input and last revised dates to Document admin

---

geniza/corpus/admin.py

Problems so far: 
* Selecting `document__description` raises an error, but `document` doesn't. Why is that?
* I've created a method `document_link` so that the read-only field links to the change page for that document, but I can't reference it in the inline. Can you not define new methods for inlines?

Stub FragmentTextBlockInline

---

geniza/footnotes/admin.py
sitemedia/css/admin-local.css

Some small changes to make the footnote inlines on both `Document` and `Source` a little easier to use.
- Remove `FootnoteInline` since it's been split into `SourceFootnoteInline` and `DocumentFootnoteInline`
- Re-add digitized transcription indicator to both inlines
- Tweak field sizing, order, and CSS so that inlines fit the screen width
Screenshot of source footnote inline:
Screenshot of document footnote inline:

Improve inline editing UI for footnotes

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py

- added prefetching to make the download generate faster
- renamed some of the methods to make the names more accurate/specific, and make it clearer they are associated with the old pgp metadata export
- adjusted the output of some of the fields to better match what I expected the content to be (my fault for not documenting more clearly and not catching in review)

Revise old pgp csv metadata view; add prefetching, tweak output #107

---

geniza/footnotes/admin.py
geniza/footnotes/migrations/0009_add_source_journal_and_footnote_url.py
geniza/footnotes/models.py
sitemedia/css/admin-local.css

@richmanrachel I'm adding url as an editable field to the inlines on document and source pages
Here's how it looks on the document edit page:
And here's how it looks on the source edit page:
Do these look ok?

Include footnote url in document and source inlines

---

geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_models.py
solr_conf/conf/solrconfig.xml

I haven't tested locally by updating my configset and reindexing (and don't have any records with old pgpids yet to test with), but I think this should do what we need.

Include old PGPIDs in solr index data and add to default search fields

---

geniza/corpus/management/commands/import_data.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_import_data.py

- propagate fgp stub technical note to db notes
- order document editions so the one with content is listed first

last minute import tweaks

---

geniza/corpus/models.py

I'm not sure why this hasn't come up in other projects, but triggering reindex on textblock change should resolve the problem that Alan noticed.
Eventually it would be nice to generalize for a solution that can live in parasolr, but I'm not going to worry about that right now.

Trigger document reindex on textblock save #239

---

geniza/settings/components/base.py
geniza/templates/admin/index.html
requirements/prod.txt

- adds & enables `django-adminlogentries`, which provides & enables a model admin for the `LogEntry` model
- adds a link to admin index view under recent actions to log entry list for the logged in user

View all admin actions

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

ref #170
screenshot of merged document history page from running locally

Include merged PGPIDs in reassociated log entries

---

.percy.yml
geniza/common/management/commands/visual_tests.py
geniza/corpus/forms.py
geniza/corpus/templates/corpus/document_list.html
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_templatetags.py
geniza/corpus/views.py
geniza/templates/base.html
sitemedia/scss/base/_breakpoints.scss
sitemedia/scss/base/_container.scss
sitemedia/scss/base/_typography.scss
sitemedia/scss/components/_metadata.scss
sitemedia/scss/components/_navigation.scss
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_searchform.scss
sitemedia/scss/main.scss
sitemedia/scss/pages/_search.scss

- Per #307:
- Implements alignment, spacing, and margin for search results page
- Implements a minimal amount of typography for those to look right
- Adds `breakpoints.respond_to` SASS mixin
- Reorders `document_list.html ` template to match order of elements in the design
- Uses individual form elements instead of `{% form %}` for finer control over layout
- Separates `document_result.html` into two containers, which act as columns in desktop and rows in mobile
- Because [element widths are defined in relation to character count](https://github.com/Princeton-CDH/geniza/blob/27c6f62c130c1a12a2d5a969ce13b79e3d9f4783/sitemedia/scss/base/_container.scss) and [spacing is defined in relation to 1rem](https://github.com/Princeton-CDH/geniza/blob/27c6f62c130c1a12a2d5a969ce13b79e3d9f4783/sitemedia …

#307 - Search results: Alignment, spacing, margins

---

geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_templates.py
geniza/corpus/tests/test_corpus_templatetags.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
requirements/prod.txt
sitemedia/scss/components/_results.scss

- configure solr highlighting on search term in description text
- render highlighting in results if present, otherwise display description excerpt as usual
I ported a `dict_item` template from one of our other codebases for an easy way to get the highlighted content for a given document.
I made a slight update to a pytest fixture in `parasolr` (our locally developed python solr client) because it made testing the assertions on the solr queryset much easier and more readable — so tests will require the develop version of that package until I release a new version.

keyword in context highlighting for search term matches in description

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/settings/components/base.py
geniza/urls.py

When I went to test the form localization (#339) I discovered I'd missed a step with the i18n setup in the url configuration; this remedies that.
I revised the permalink url logic so it does _not_ include a language code: this way all versions of a document will show the same url for citation purposes, but it will resolve to the user's preferred language or the site default.
Note that this means there's now a difference between `get_absolute_url` and `permalink`; this is because I think the absolute urls we're generating elsewhere should be relative to the currently active language.
changes in this PR:
- adds `i18n_patterns` to main url config for public site urls (currently only `corpus`)
- revise document permalink behavior so it is language independent 
- adjust tests for the change to …

Configure public site urls for i18n

---

sitemedia/scss/base/_typography.scss
sitemedia/scss/components/_navigation.scss
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_searchform.scss
sitemedia/scss/components/_tag.scss
sitemedia/scss/pages/_search.scss

- Per #309:
- Implements type sizes for the search page according to the designs
- Removes the underline from "View document details" link per designs
- Slightly reorganizes CSS to prevent the same selector from having two separate definitions
- As I mentioned previously, the type sizes are defined relative to the page root—in terms of `rem`—rather than absolute `px` values. I went ahead and tried to match the values as closely as I could. I mapped it like this:
- 16px --> `$text-size-md: 1rem;`
- 18px --> `$text-size-2md: 1.15rem;`
- 20px --> `$text-size-lg: 1.25rem;`
I don't believe there are any font sizes besides those in the designs.
- I feel like the "View document details" type looks massive on desktop, but it's matching the design at 20px, the same size as the document title. It …

#309 - Search page type sizes

---

geniza/corpus/templates/corpus/document_list.html
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/base/_a11y.scss
sitemedia/scss/components/_searchform.scss

Might have made more sense to roll this in with #345, but I had already created a new feature branch for it!
- Per #310:
- The bulk of this was already accomplished in #336
- Fixes some issues with form elements on different screen sizes via better use of `max-width`
- Per #311:
- Changes the search submit button into an icon button using the Phosphor magnifying glass
- Hides the search button on mobile, but leaves it accessible to screen readers
- Question for @rlskoeser: Should `aria-label` names be translated?

#310, #311 - Implement search box and button styles

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
sitemedia/scss/base/_typography.scss

- Per #354:
- Updates `Document` model `title` property, which is used in document detail view head metadata 
- Updates `_typography.scss`, which is used in search results page, and document detail view title header
- Updates tests to use colon

#354 - Replace semicolon with colon in doc titles

---

geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_templates.py
sitemedia/scss/components/_results.scss

updates the scholarship display on the public search
- fix a bug where 1-counts for scholarship records were not displayed
- revise layout to match the latest revisions in the design (#338) and update tests accordingly
- use `blocktranslate` to handle pluralization properly

Revise & correct scholarship counts for search

---

geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/tests/test_corpus_templates.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/pages/_document.scss

- Per #231:
- Adds an "Edit" link (with Phosphor pencil icon) to the document detail view template for those with appropriate permissions
- Adds template test for the above

#231 - Add "edit" link to document detail view for admins

---

geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_templates.py

update template highlighting for latest version of parasolr `AliasedQuerySet`, which now handles aliased fields in highlighting results

Update highlighting to work with latest parasolr

---

sitemedia/scss/components/_tabs.scss

Per https://github.com/Princeton-CDH/geniza/issues/313#issuecomment-985625133:
- Uses `display: inline-block` and padding for document tabs links, ensuring that the space around the text is clickable

#313 - Use inline-block for tab links

---

geniza/corpus/models.py
geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_templates.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/pages/_document.scss

Per #390:
- Only shows brief citations relating to digital editions on Document Detail page
- Pluralizes "Editor" label when there is more than one editor of digital edition(s)
- Shows "unpublished" in brief citations when applicable
- Updates the display of brief citations with "notes" to always end in a period
- (Finally!) disables phosphor "i" icon next to permalink

#390 - Brief citations for digital editions

---

geniza/corpus/management/commands/import_manifests.py
geniza/corpus/models.py
geniza/corpus/tests/test_import_manifests.py
geniza/settings/components/base.py
requirements/prod.txt

I'm not certain this is the approach I want to use for the long-term, but for the MVP I'm going to go ahead with the approach I've used before. 
in this PR:
- add djiffy to requirements and installed apps
- local import manifest command to import iiif manifests based on urls associated with fragments
- notes about possible integration between manifest and fragment

Setup djiffy and add basic script to import IIIF manifests

---

geniza/common/management/commands/visual_tests.py
geniza/corpus/fixtures/ui_ux_test_documents.json
geniza/corpus/templates/corpus/document_scholarship.html
geniza/corpus/tests/test_corpus_templates.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/components/_footnote.scss

- Per #389:
- Changes "includes" text to "see [`footnote.location`] for"
- Links that text to `footnote.url` if it exists
- Links work title to `source.url`
- Adds "unpublished" label to unpublished sources on scholarship records page
- Adds a new document to fixtures that better represents the scholarship records page

#389 - Update source/footnote "includes" section

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_tag.scss

[Percy build](https://percy.io/3201ecb4/geniza/builds/14498261)
- In scope: just checking that the tags look right on mobile and desktop search results pages
- Type sizes, etc. are still forthcoming in another PR
- Limits the maximum number of tags displayed in search results to 5
- Per #382:
- In search results, moves tags below scholarship records counts, above "View Document Details" link

#382 - Move tags below search result description

---

geniza/common/management/commands/visual_tests.py
geniza/templates/base.html
lighthouserc.js
sitemedia/scss/base/_fonts.scss
webpack.config.js

- use `/static/fonts/` prefix for purchased fonts
- configure webpack css loader not to load urls

Tweak fonts webpack config

---

geniza/corpus/management/commands/add_links.py
geniza/corpus/tests/test_add_links.py

- Per #325, revises the add links script to add:
- Escaped URLs to fix admin interface bugs
- Footnote location generation / assignment
- A report of documents not found
I just decided to save the "documents not found" report to the same directory as the original CSV. I also appended the original CSV's basename to the filename, in case multiple reports will be generated in the same directory for different CSVs.
Also, I reordered some of the logic in `test_add_link` to minimize the amount of times `link_target` is updated to reflect the kind of `link_target` that we expect from each document type.

#325 - Add links script revisions

---

DEPLOYNOTES.md
geniza/templates/snippets/language_switcher.html
sitemedia/scss/components/_langswitcher.scss

When I saw the language switcher in qa I immediately saw we didn't have it quite right! It is probably still not great and will benefit from Gissoo's design input when she is able to get to it, but wanted to make a quick adjustment for now:
- display "read this page in ..." in the language that will be switched _to_, so it's readable to a user who can't read the site text in the current language
- add dir=rtl in css for hebrew & arabic options

Tweak language switcher

---

geniza/common/tests.py
geniza/common/utils.py
geniza/settings/components/base.py

Django-taggit allows for multi-word tags, but `TaggableManager` does not encourage users to input them correctly 🥴 Should I open a ticket on https://github.com/jazzband/django-taggit?

Implement django-taggit multi-word bugfix

---

geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/urls.py
geniza/corpus/views.py

proof-of-concept implementation to allow downloading transcription content as plain text, to see if this will satisfy the functionality needed for #434

Make transcription available for download as text

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py

tweaks the keyword search to convert aliased solr field names into actual solr fields so that we can allow users to do more powerful searches within the existing keyword search field; specifics are documented on #494 
(note that this also makes it possible to easily support tag searching)

Convert solr alias fields in keyword search terms

---

geniza/corpus/admin.py
geniza/corpus/tests/test_corpus_admin.py

ref #507
the empty admin list filter stopped working reliably after a recent update; this PR implements a custom filter that keys directly on the html content set by the `sync_transcription` script, and the numbers seem much better

Custom admin filter for documents with transcription

---

geniza/corpus/admin.py
geniza/corpus/tests/test_corpus_admin.py

@blms when I went to deliver the document deletion bug fix I discovered that we still hadn't solved the problem! the deletion view used the custom queryset, so it still had the log entries relation with the permissions problem. However, I figured out that once that queryset customization was in place, I could override just the `get_deleted_objects` method to make sure _that_ one uses the non-proxy `Document` model without the generic relation causing all our permission problems.

Override DocumentAdmin get_deleted_objects

---

.github/workflows/visual_tests.yml
README.rst

- Per #513:
- Updates the `visual_tests` workflow (aka Percy screenshots) to only run if the message `[run percy]` is present in the commit message, or if the trigger is a push to the `develop` branch

#513 - Require message when taking Percy screenshots

---

geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_templates.py

Turns tags in search results & document detail page into links to a tag search
This will change the percy build, but I can't tell from the designs on Figma if the default link style is what's intended for tags.

Link tags to search documents by tag

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

When indexing document via prefetch proxy,
index data should be the same when indexed as a document

Correct document prefetch index type

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py

- attribution is optional
- use images from cached manifest when available

improve IIIF handling so it works with PUL/JTS content

---

geniza/corpus/admin.py
geniza/corpus/templates/admin/corpus/document/change_list.html
geniza/corpus/templates/admin/corpus/review_list.html
sitemedia/css/admin-local.css

Had an idea about a different way to solve the "needs review" queue display problem — add a toggle to the template and control the display with css. What do you think?

needs review alternate view for document admin list display

---

geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py

- Per #486:
- Adds source volume for unpublished sources back to the `__str__` method; adds a new method `formatted_stripped` to allow displaying without it
- I think the only other place the source string method was called, besides the admin interface, was `footnote.display()`. Otherwise the frontend uses `source.formatted_display()`. Running Percy just in case! (edit: confirmed in Percy)

#486 - Add volume back to unpublished source string method

---

geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_templates.py
sitemedia/scss/components/_tag.scss

Two questions:
* Do we want to make a `max_tag_count` for the template? Because it shows up in different forms each times it's used (e.g. as a string in a slice, as an int for a boolean, and as a negative string for the `add` function), I'm not sure how much value it would add.
* Please confirm that the image below is the wording and appearance you need. The `#` at the start is controlled by a CSS `:before` element, which I don't think I can change in-line. Before I start on that, would you mind confirming that this is what we were generally shooting for?

522 show many tags

---

geniza/corpus/models.py
geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templates/corpus/snippets/document_header.html
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/templates/corpus/snippets/document_shelfmarks.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_templates.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
sitemedia/scss/components/_docheader.scss
sitemedia/scss/components/_shelfmark.scss
sitemedia/scss/main.scss

- Per #547:
- Removes `shelfmark_display` method, and instead just uses shelfmark string method to display all shelfmarks in document titles
- Removes footnote location from detail view; moves test for footnote location presence to scholarship records template
- Fixes "download edition" link for sources with no authorships

#547 - Document detail view tweaks

---

geniza/corpus/templates/corpus/document_scholarship.html
geniza/corpus/templates/corpus/snippets/footnote_location.html
geniza/corpus/tests/test_corpus_templates.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/components/_footnote.scss

- Per #501:
- Rearranges footnote relations/locations to read "for Relations see," then a line break, then list of footnote locations
- Uses "includes Relations" for footnotes with no locations or URL
- Uses "online resource" placeholder for footnotes with a URL and no location
- Uses [no title] placeholder in long-form citations for sources without titles

#501 - Footnote location/URL revisions

---

.github/workflows/lighthouse.yml
geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templates/corpus/snippets/document_tabs.html
geniza/corpus/templates/corpus/snippets/document_transcription.html
geniza/corpus/tests/test_corpus_templates.py
geniza/templates/base.html
lighthouserc.js
sitemedia/scss/components/_iiif.scss
sitemedia/scss/components/_tabs.scss
sitemedia/scss/pages/_document.scss

- Per #488:
- Pins Lighthouse CLI to 0.8.x, as 0.9 drops support for Node 12
- Disables `unused-javascript` and `unsized-images` warnings that are only broken by OpenSeaDragon
- Increases tap target sizes for tags on document detail view
- Fixes invalid heading hierarchy
- Uses `aria-disabled` and `disabled` attributes to ignore contrast on disabled elements
- Uses `link rel="preconnect"` for unpkg
- Adds home page to Lighthouse tests

#488 - Address lighthouse errors

---

geniza/corpus/tests/test_corpus_views.py
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

ref #468
add another solr configuration and copy field for shelfmarks to index letters and numbers only, ignoring punctuation and so that portions of shelfmarks like `20.169` will be split apart and made available for partial matching.

Improve shelfmark indexing

---

geniza/corpus/templates/corpus/snippets/document_tabs.html
geniza/corpus/tests/test_corpus_templates.py

@blms I think maybe this got missed when you fixed the lighthouse checks — please confirm

Add disabled attributes for empty scholarship tab

---

requirements/prod.txt

Looks like this worked for now, maybe the new update to Wagtail (3 hours ago!) broke something with wagtail-localize—I'll keep an eye on it.

Pin Wagtail requirement at <2.16

---

geniza/corpus/forms.py
geniza/corpus/templates/admin/corpus/document/merge.html
geniza/corpus/templates/corpus/snippets/document_option_label.html
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_forms.py
geniza/corpus/views.py
sitemedia/css/admin-local.css

- Per #225:
- Changes scholarship records from `details` back to `div` so that all are visible in document merge
- Changes verbiage "primary document" to "select primary document"
- For rationale: uses radio buttons with "other" and an optional notes field, which becomes required if "other" is selected
- Sets "duplicate" as default choice
- I didn't include labeling transcriptions in the admin, or expanding all trancsriptions on the front end, in this PR. I was thinking it's best to get this stuff reviewed first and do that separately, since it's a different concern.

#225 - Admin document merge tweaks

---

geniza/corpus/templates/admin/corpus/document/change_form.html
sitemedia/css/admin-local.css

- Per #596:
- When displaying multiple transcriptions in the document admin: groups transcriptions by source, labels them each with source citation

#596 - Show transcription source labels in admin

---

geniza/footnotes/migrations/0016_rename_typed_texts.py

- Should the migration query on and update just `title_en`, or `title` as well (as I currently have it)?
- I guess it wasn't caught by tests because I do set the `title` field directly when instantiating the Source records. I guess that doesn't automatically populate the `title_en` field as well. Should I be setting `title_en` there instead as well?

#589 - Use appropriate modeltranslation fields for "typed texts" source migration

---

DEPLOYNOTES.md
geniza/corpus/models.py
geniza/corpus/templates/corpus/snippets/document_transcription.html
geniza/corpus/tests/test_corpus_models.py
requirements/prod.txt

- Per #560:
- Adds a function that gets a single Fragment's attribution; from local or remote manifest
- Updates transcription template to show attribution per shelfmark
- Updates djiffy to 0.7.2
- Adds deploy notes
- I left the old code present in case we still want to use it for serving our own IIIF manifests.

#560 - Get attribution per fragment/shelfmark

---

geniza/corpus/templates/corpus/snippets/pagination.html
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
sitemedia/scss/components/_pagination.scss

revisions to random sort:
- remove previous random seed logic to preserve current random order when paging through a particular randomly ordered set
- disable pagination on document search page if sort is random
- if a page other than 1 is requested when sort is random, redirect to the first page of results

Only allow first page when sort is random

---

geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_templatetags.py

- Per #578:
- Adds a template filter to convert all instances of "PGPID ###" in a passed text into links to the canonical URL to the referenced document
- Applies that template filter to the description in the document detail view

Template filter for automatic PGPID links in descriptions (#578)

---

geniza/common/management/commands/visual_tests.py
geniza/corpus/templates/corpus/document_list.html
sitemedia/js/controllers/search_controller.js
sitemedia/scss/components/_searchform.scss

- Ensures search sort is not random for Percy
- Per #663:
- Positions filters absolutely and aligns with the "Filters" text in the search form, on desktop
- Leaves mobile functionality the same as before

Position search filters absolutely on desktop (#663)

---

geniza/corpus/templates/corpus/document_detail.html
geniza/templates/base.html

- Per #386:
- Escapes title, description, and editor metadata fields to avoid breaking on double quotes and other problem characters

Escape potential problem metadata fields (#386)

---

geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py

* We want to track all fields correct? Let me know if I should add a filter.
* Looks like next time we do a release for parasolr we should make sure to rebuild the docs. https://parasolr.readthedocs.io/en/latest/search.html?q=SolrLastModifiedMixin&check_keywords=yes&area=default

Add parasolr last modified mixin (#375)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_signals.py

@rlskoeser I got a bit caught up on the fact that parasolr can't handle foreign/generic keys. Throwing this together last minute, and tests need to be written, but just let me know if I'm missing something big!

Automatically reindex documents when sources, footnotes, or creators change (#668)

---

.github/workflows/visual_tests.yml
.percy.yml
geniza/corpus/templates/corpus/document_list.html
geniza/settings/environments/test.py
sitemedia/scss/components/_searchform.scss

In order to move page content down, instead of overlaying the expanded filters on top of the form and results:
- Rearranges the search options so that filters sit between the filter toggle button and the sort options
- Uses relative positioning and negative margins to position the expanded filters

Position filters relatively on desktop (#663)

---

geniza/common/management/commands/visual_tests.py
sitemedia/scss/components/_navigation.scss

- Per #411:
- Uses `visibility: hidden` to hide mobile menus when off screen

Fix issue with mobile menus appearing from off-screen (#411)

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/scss/components/_results.scss

- Per #648 
- In search results: moves the result number span outside of the section element used for metadata, adds a span element in the view link, and uses flexbox styling to ensure that the width of the left margin grows and shrinks to accommodate the number

Fit search result number left margin to content (#648)

---

sitemedia/css/admin-local.css

- Per #688:
- Uses `text-align: right` in admin CSS for transcriptions
I think fixing this is as simple as aligning the text right, as it is in search results, but this comment gave me pause:
```css
/* left-aligned transcriptions; rtl is controlled thru html "dir=" attribute */
```
I realized the reason why it reverted to left-alignment is because of the Django fieldset and div classes I used to make transcriptions look nice in the admin interface. But I want to make sure I'm not missing some intention here behind the comment!

Right align transcriptions in admin (#688)

---

geniza/templates/base.html

- Per #700:
- Fixes bug causing social media preview to fail by applying `escape` template tag independently of `firstof` check

Fix title and description metadata bug (#700)

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/scss/components/_results.scss

- Per #648:
- Implements a revision of the previous search numbers flex spacing CSS, giving the description enough room to accommodate 5 digit numerals without causing a wrap

Revise search numbers flex spacing (#648)

---

geniza/corpus/templates/corpus/snippets/document_header.html
sitemedia/js/controllers/text_controller.js
sitemedia/scss/components/_docheader.scss

- Per #705:
- Uses CSS to improve ability to select shelfmarks in the document detail page
- Adds preliminary functionality (commented out) for "click to copy"

Improve shelfmark selection (#705)

---

geniza/templates/base.html
sitemedia/webpack-stats-ci.json
webpack.config.js

- Fixes an error with `webpack-dev-server` that required loading the JS output of a bundle (even if empty) alongside any CSS, by simply combining the two bundles into one

Combine all webpack js/css into one bundle

---

geniza/corpus/templates/admin/corpus/document/change_form.html
geniza/corpus/templates/corpus/snippets/document_transcription.html
geniza/templates/base.html
sitemedia/css/admin-local.css
sitemedia/js/iiif.js
sitemedia/js/main.js
sitemedia/scss/components/_iiif.scss
sitemedia/scss/iiif.scss
sitemedia/scss/main.scss
sitemedia/webpack-stats-ci.json
webpack.config.js

- Per #724:
- Uses the template, JS, and CSS from the document detail view IIIF viewer in the admin UI
- Changes the `has_transcription` check to `digital_editions`, since otherwise it was showing an empty transcription container in the admin UI
- Converted `H1` to `H3` in all transcriptions to avoid the "language dropdown" issue (I hate that they attach that to ALL `H1` elements!)
- Splits IIIF viewer JS/CSS into a separate bundle to allow only loading that, and not the other JS/CSS, in admin
- I had to include the `iiif` Webpack bundles in `base.html` rather than `document_detail.html` in order for Turbo to pick them up. Not entirely sure why that is, but also not sure if it's worth investigating since we were already including that JS/CSS before in `base.html` anyway.

Use IIIF viewer from doc detail view in admin UI (#724)

---

sitemedia/scss/components/_controls.scss
sitemedia/scss/components/_navigation.scss

- Per #749:
- Moves the "burger" main menu button to the corner on mobile, and moves the light/dark toggle to accommodate its new position

Revise placement of "burger" menu (#749)

---

geniza/corpus/templates/corpus/snippets/document_permissions.html
geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/scss/components/_iiif.scss

- Per #775
- Fixes focus style for image permissions details/summary element
- Includes the fragment's `url` (view url) as link on shelfmark, if available

Permissions statement revisions: focus, fragment view url (#775)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

- Per #779:
- Adds a comma between original date and calendar name
- Does this make sense? I wanted to make the function as simple as possible while allowing either original date or calendar name to be blank, but it still reads a bit weird.

Separate date and calendar with comma when needed (#779)

---

sitemedia/scss/components/_tabs.scss
sitemedia/scss/pages/_document.scss

- Per #774:
- Aligns navigation tabs with content in the document detail view
- Reduces metadata spacing in the document detail view

Document detail view revisions (#774)

---

geniza/corpus/admin.py
geniza/corpus/models.py
geniza/corpus/templates/corpus/snippets/document_header.html
geniza/corpus/tests/test_corpus_models.py

changes:
- implemented a `label` property that displays combined shelfmark or shelfmark override if set
- use the new label field for indexing shelfmark in solr for display
- label is displayed in search results, document title, document metadata, admin document change list
- actual shelfmark is displayed in metadata and shelfmark display field on document change form
question:
Is `label` confusing since we already have a `title` property? maybe `shelfmark_label` ? `shelfmark_display` ?

Revise logic for when shelfmark override is displayed

---

geniza/corpus/templates/corpus/snippets/document_image_rights.html
sitemedia/scss/components/_iiif.scss

- Per #802:
- Displays unique logos in a list below the list of fragment attributions, with preliminary/basic styling
- Prevents an extra space from being added between the shelfmark and colon in the image permissions section
- What do you make of the `alt` text? I think using the name of the organization would be preferable (and would be good for a `title` attribute as well), but I couldn't figure out a way to get that from the manifest.
- Using `ifchanged` is sufficient to guarantee uniqueness for all of my local data, but it somewhat depends on the order of fragments retrieved. Is there some way we should order the fragments first, or should the uniqueness not be handled in the template?

Implement basic solution for displaying IIIF logos (#802)

---

sitemedia/scss/components/_navigation.scss

- Per #839:
- Fixes issue with hamburger menu overlapping light/dark toggle by absolutely positioning the hamburger menu, and defining its distance from the right edge (LTR; left edge RTL)

Absolutely position hamburger menu (#839)

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_tag.scss

- Per #769:
- Removes "PGP ID" translation in search results
- Aligns transcription to flex-start in RTL search results, since they are RTL content and should be right-justified
- Aligns tags according to design

Adjust RTL search results page tags/transcription and remove "PGP ID" translation (#769)

---

sitemedia/js/controllers/search_controller.js

- Per #827:
- Only auto-switch to relevance sort (by typing in the search query field) when the default sort element is checked

Only auto-sort by relevance from default sort

---

geniza/common/fields.py
geniza/common/templates/common/widgets/rangewidget.html
geniza/common/tests.py
geniza/corpus/dates.py
geniza/corpus/forms.py
geniza/corpus/models.py
geniza/corpus/sitemaps.py
geniza/corpus/templates/corpus/document_list.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_dates.py
geniza/corpus/views.py
sitemedia/scss/base/_colors.scss
sitemedia/scss/components/_searchform.scss
solr_conf/conf/managed-schema

in this pr:
- define date range field type in solr schema (requires updating configset)
- index standardized dates as date range in solr
- port range filter & widget from other CDH codebases
- display range filter on form (preliminary / unstyled)
- implement range filtering in the document search view
does not include styles or placeholder text; unit tests are incomplete
questions:
- The range input I ported over uses integer fields. Technically we could support YYYY-MM-DD, but Marina indicated year was sufficient and I'm not sure we need the additional complexity (number input is easier to validate). However, I'm not sure if we can add placeholder text to a numeric input, which might be reason enough to switch (maybe).

filter and sort documents by date

---

geniza/corpus/dates.py
geniza/corpus/management/commands/convert_dates.py
geniza/corpus/tests/test_convert_dates.py

in this PR:
- revise `convert_dates` manage command to add modes, make current logic the `report` mode
- added an `update` mode, which converts dates with supported calendars & formats into the new format
- added a `clean` mode, which identifies standardized dates that don't follow the new validation pattern and cleans up the ones that can be automatically fixed
still needs tests & documentation

Add update & clean modes to convert dates script

---

geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/templates/admin/corpus/document/change_form.html
geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templates/corpus/document_scholarship.html
geniza/corpus/templates/corpus/related_documents.html
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/templates/corpus/snippets/document_tabs.html
geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_templates.py
geniza/corpus/tests/test_corpus_templatetags.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/urls.py
geniza/corpus/views.py
sitemedia/scss/components/_metadata.scss
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_tabs.scss
sitemedia/scss/main.scss
sitemedia/scss/pages/_document.scss
sitemedia/scss/pages/_related.scss
sitemedia/scss/pages/_scholarship.scss
sitemedia/scss/pages/_search.scss

in this pr:
- initial view & template for new related documents page (replaces placeholder "external links")
- solr query to find other documents that share any of the same shelfmarks
- update document tab template to display related docs link with count
- adjust document result template to work with or without pagination object
- simplify page description for scholarship record & related docs (document title is redundant)
- update existing tests for external links tab behavior
no tests yet for new methods/views/templates; no updates to styles

Related documents page

---

geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/iiif_controller.js
sitemedia/scss/components/_transcription.scss

- Per #937:
- Remove OSD icons preconnect
- Implement basic rotate controls with phosphor icons
- Should the rotation controls always be enabled? For now, I've disabled them when deep zoom isn't enabled; I know we discussed eventually allowing users to enable/disable OSD using the rotation controls, but not sure if that makes as much sense for the MVP version. The strict 90º rotation could be quite jarring; it makes the transition much harder to handle, certainly. And not sure if a deactivation state should exist with this rotation control. But I can also easily see it being confusing to have the rotation controls simply disabled until you start zooming. Wonder if there's a good interim solution?
- With taller images, some surprising OSD stuff can happen on rotation. I noticed that the …

Basic rotation controls for ITT panel on desktop (#937)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/iiif_controller.js
sitemedia/scss/components/_transcription.scss

- Per #891:
- Fix issues with scrolling by putting OSD in its own container and constraining its height
- Use Stimulus targets rather than DOM queries to refer to elements
- Should we increase the width of OSD when only images are checked? In that case, we'd need some way for Stimulus to pick that up, such that we could modify `resetBounds` to position OSD according to the static image. In addition, the following CSS would be required:
```scss
#images-on:checked ~ .panel-container {
[...]
// image panel spacing
div.img {
margin: 0 auto;
overflow: visible;
.deep-zoom-container {
overflow: visible;
}
.osd {
width: 100vw; // Some other width?
}
}
}
```
Not sure what width makes the most sense though, 100vw might be overkill.

Deep zoom revisions (#891)

---

geniza/corpus/templates/corpus/document_transcribe.html
geniza/corpus/views.py
geniza/settings/local_settings.py.sample
sitemedia/scss/components/_annotation.scss

- Per #916:
- In tandem with https://github.com/Princeton-CDH/annotorious-tahqiq/pull/5, allow editing using TinyMCE.
After spending some hours debugging bundling errors, I chose to use the CDN rather than Webpack. Hopefully that's OK! (For what it's worth, this is also [Tiny's recommendation](https://www.tiny.cloud/docs/tinymce/6/webcomponent-pm/))

Include TinyMCE from CDN in transcribe view (#916)

---

sitemedia/scss/components/_navigation.scss

- Per #967:
- Fix mistake where light mode "header-filler" was being used in dark mode
- Fix incorrect offset for "header-filler" on desktop

Fix issue with header on wide displays (#967)

---

DEPLOYNOTES.md
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
sitemedia/css/admin-local.css

- Per #955:
- Add `selected_side` param to `Fragment.iiif_thumbnails()`; use in `TextBlock.thumbnail`
- Use that to set a class `"selected"` to the thumbnail of the selected side, and add some styling to the admin CSS
- Per #956:
- Add `filter_side` param (filter by each `TextBlock`'s side) to `Document.iiif_images()`; use in solr indexing
(asked on Slack but here is probably better)
1. For side filtering, should we go by index of the image (ie assume first image always = recto) for all methods? I only saw it mentioned for `iiif_thumbnails` so wasn’t sure if I should take the same approach on `Document.iiif_images`
- I took an approach using labels in f7b102a and 073d023, but reverted to going by order—wondering if that's the direction we're going or if we should just go by order for now. …

Filter/select side in IIIF image/thumbnail methods (#955, #956)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/transcription_controller.js
sitemedia/scss/components/_transcription.scss

- Per https://github.com/Princeton-CDH/geniza/issues/959#issuecomment-1194461536, fixes the transcription switcher (#899) for documents with no images. (It was not working at all before due to missing Stimulus targets)
Similar to how the chunking index in documents with images relies on the number of images, the chunking index here relies on the number of chunks in `digital_editions.0`. I wonder if we should come up with a different way to handle chunk indices, since that's also the problem we're having with https://github.com/Princeton-CDH/geniza/pull/969?

Fix transcription switcher on docs w/ no images (#899), use full citation (#959)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
package-lock.json
package.json
sitemedia/js/controllers/iiif_controller.js
sitemedia/scss/components/_transcription.scss
webpack.config.js

- Per #978:
- Replace +/- 90º rotation with `angle-input` library, new design
- The Webpack IgnorePlugin is required because of a line `require("jquery")` in the angle rotation library, which Webpack will evaluate even if you aren't using the jQuery part of the library. Fortunately, the library doesn't list `jquery` in its requirements, so we aren't forced to include it in the bundle; instead, we need to tell Webpack specifically to ignore this `require` statement.
- I added this section to support rotation events on desktop that aren't triggered by the angle input, as I recalled from our meeting that @rlskoeser found it was possible. But I don't have a Magic Trackpad or similar, so I have no way of testing if this works. Please check to make sure that the angle input updates its UI when …

Implement angle rotation (#978)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html

The use of `|safe` inside a data attribute of an element was causing broken HTML. This PR removes it and leaves the HTML escaped in that context.

Unmark HTML safe in data attribute (#959)

---

package-lock.json
package.json
sitemedia/scss/components/_annotation.scss
sitemedia/scss/components/_transcription.scss

- Per https://github.com/Princeton-CDH/geniza/issues/916#issuecomment-1194136341:
- Style superscript
- Style line numbers (in transcribe view; main view uses data attribute)
- Update tahqiq to allow editing empty annotations
- We will probably need to update the commit hash once [the tahqiq PR](https://github.com/Princeton-CDH/annotorious-tahqiq/pull/11) is merged
- How should we handle the discrepancy between the line numbering between the editor (plain `<li>` elements) and the existing TEI transcriptions (`<li>` elements with `data-value` attributes)? Something to think about for the upcoming changes to transcription format, maybe?
- Should there be some kind of validation to ensure content in the annotation body?

Fix missing styles on transcription editor (#916)

---

sitemedia/js/controllers/iiif_controller.js

- Remove handler on viewer to handle gesture "rotate" events triggered by interaction with the canvas itself, since per https://github.com/Princeton-CDH/geniza/pull/979#pullrequestreview-1051011969 gesture rotation doesn't seem to work on desktop anyway (and I can't test it)
- Per https://github.com/Princeton-CDH/geniza/issues/978#issuecomment-1195959854:
- Snap rotation to 0 degrees within +/- 5

Snap rotation to 0 within +/- 5 degrees (#978)

---

sitemedia/scss/components/_controls.scss
sitemedia/scss/components/_footer.scss
sitemedia/scss/pages/_document.scss

- Per #989:
- Hide theme toggle below transcription panel (extending permalink area to cover the bottom)
- Rotate clockwise from light -> dark, then counter-clockwise from dark -> light

Light/dark toggle revisions (#989)

---

geniza/annotations/tests/test_annotations_views.py
geniza/annotations/views.py
geniza/corpus/templates/corpus/snippets/document_transcription.html
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/urls.py
geniza/corpus/views.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
package-lock.json
package.json
sitemedia/js/controllers/annotation_controller.js
sitemedia/scss/components/_transcription.scss

- Per #913:
- Add `Source.uri` property
- Allow searching annotations on `dc:source`/source URI
- Pass source URI to Tahqiq when editing existing transcription
- Should I raise `Http404` here if the source could not be found and `source_pk` is not None? (It will always be None when a user clicks "Add a new transcription")
https://github.com/Princeton-CDH/geniza/blob/12515f671a1f279ddd3175ecd9c40364c07d4d85/geniza/corpus/views.py#L669-L675
- Note: the latter behavior may change depending on our approach in https://github.com/Princeton-CDH/geniza/pull/1005 (e.g. https://github.com/Princeton-CDH/geniza/pull/1005/commits/71f5a2475ba7fb9d5e560543f0e993bc5b2a2cfc)

Link annotations to scholarship records (#913)

---

geniza/common/utils.py
geniza/corpus/apps.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_signals.py

- Per #943:
- Adds `pre_save` signal to `taggit.Tag` to ensure `unidecode` is run on the `name` field of model instances created manually, not just on related save of a tagged instance of another model.

Unidecode all tags on pre_save signal (#943)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
sitemedia/img/ui/all/all/recto-placeholder.svg
sitemedia/img/ui/all/all/verso-placeholder.svg

- Per #1023:
- Use placeholder SVG images when no IIIF image available, to allow editing side info with the same UI

Allow editing side info when no IIIF images present (#1023)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/components/_transcription.scss

- revises the related document link on non-document images so translators can work with it (previously it had too many tokens and included tags)
- regenerated the translation files to incorporate the change
- adjusts the related document link to match the designs (both type and shelfmark should be bold)
@blms please review and adjust the styles as needed, something looks a little bit off to me with the font styles or line heights (discrepancy between "view" and the document label)

Adjust related doclink text for translators

---

geniza/annotations/models.py
geniza/annotations/signals.py
geniza/annotations/tests/test_annotations_signals.py
geniza/annotations/tests/test_annotations_views.py
geniza/corpus/templates/corpus/document_transcribe.html
geniza/corpus/views.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
sitemedia/scss/components/_annotation.scss

- Per #1000:
- Ensure document is reindexed when annotation content changes
- Per Slack:
- Cite full scholarship record in header of transcribe page
-  The test in `test_annotations_views` was failing because it tries to index the document, and the unexpected value for `body` (a string) was causing an error in the `content_html` method, which is called during indexing. Is this the right way to handle that, or are there possible other kinds of `body` in the real world we should handle? (Or should we just be mocking indexing altogether during this test?)

Reindex document on annotation update (#1000)

---

sitemedia/scss/components/_annotation.scss
sitemedia/scss/components/_transcription.scss

- Per #1038:
- Remove counter from `<ol>` lists in transcription content, and use the decimal list style, so that line numbers respect the HTML start attribute
- Adjust margin/padding to adjust for line number marker pseudo-elements

Revise ordered list style to use actual line numbers (#1038)

---

sitemedia/scss/components/_transcription.scss

- Per #1038:
- Increase margin on line number markers to allow space for 2 digits

Transcription line number margin for 2 digits (#1038)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

Rachel flagged this in testing, IDK if we have an issue anywhere that would make sense to test it  — in some cases after the migration we only have a digital edition footnote and no editions, and in the search results those records display as having no transcriptions, which is obviously false. This is a simple fix to make sure we count digital editions when tallying up editions.

Count digital editions as editions when indexing

---

package-lock.json
package.json
sitemedia/scss/components/_annotation.scss

- Per #1021:
- Bumps tahqiq to version including annotation reordering
- Per #1022:
- Bumps tahqiq to version including moving annotations between canvases
- Styles drop zone for canvases without annotations
See also https://github.com/Princeton-CDH/annotorious-tahqiq/pull/13

Bump tahqiq commit hash, style drop zone (#1021, #1022)

---

geniza/corpus/templates/corpus/document_transcribe.html
geniza/corpus/views.py
package-lock.json
package.json
sitemedia/js/controllers/annotation_controller.js

- Per #1065:
- Pass the Tiny API key along to tahqiq, instantiate Tiny via the web component rather than a direct call to the CDN JS
- Bump tahqiq commit hash

Pass Tiny API key to tahqiq, remove Tiny CDN JS from header

---

geniza/corpus/models.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
geniza/footnotes/utils.py
sitemedia/css/admin-local.css
sitemedia/scss/components/_results.scss

- Per #1049:
- Use an `HTMLParser` subclass to parse transcription html and add line number `value` attributes
- Restore CSS to show those attributes as line numbers in search results
- Fix admin CSS issue with line number suppression

Add line numbers to transcription lines in indexed html (#1049)

---

sitemedia/scss/components/_annotation.scss
sitemedia/scss/components/_transcription.scss

- Per #1039:
- Make missing image placeholders transparent outside of transcription editor
- Clean up css comments for transcription editor

Transparent placeholders (#1039)

---

geniza/templates/base.html
sitemedia/scss/components/_controls.scss
sitemedia/scss/components/_navigation.scss

- Per #1090:
- Move light/dark toggle into `header` landmark so that there is no page content outside landmarks
- Following [these recommendations](https://dequeuniversity.com/rules/axe/4.1/region), separate `nav` and `header` into adjacent landmarks
I also tested z-index to make sure all still works as expected with the nav, light/dark toggle, and language switcher.

Move nav outside, and theme toggle inside, header (#1090)

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/scss/base/_global.scss
sitemedia/scss/base/_typography.scss
sitemedia/scss/components/_docheader.scss
sitemedia/scss/components/_footer.scss
sitemedia/scss/components/_footnote.scss
sitemedia/scss/components/_iiif.scss
sitemedia/scss/components/_metadata.scss
sitemedia/scss/components/_navigation.scss
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_searchform.scss
sitemedia/scss/pages/_content.scss
sitemedia/scss/pages/_document.scss
sitemedia/scss/pages/_error.scss

- Per #1106:
- Implement all new Hebrew type styles from Figma, using new mixins and specifying new rules for `html[lang="he"]`
- Use `calc()` for calculating line height proportions, instead of manual calculation (using proportions instead of pixels for scaling)

Implement new Hebrew type styles (#1106)

---

geniza/corpus/forms.py
geniza/corpus/templates/corpus/document_list.html
geniza/corpus/tests/test_forms.py
sitemedia/js/controllers/search_controller.js
sitemedia/scss/components/_searchform.scss

- Per #1089:
- Remove `SelectDisabledMixin` and `RadioSelectWithDisabled`, and revert form widget to default `select` element
- Remove details/summary/button from HTML and revert to form default widget; add icon for caret-down (presentation only)
- Remove Stimulus logic for control of the custom listbox, and adapt Stimulus logic for "relevance" option enabling/disabling
- Adapt CSS for `select` element and Phosphor icon

Revert sort listbox to <select> in search form (#1089)

---

DEPLOYNOTES.md
geniza/corpus/annotation_export.py
geniza/corpus/management/commands/sync_annotation_export.py
geniza/corpus/tests/test_annotation_export.py

Finishes initial implementation (without co-author commits) for updating annotation backup data via signal handler.
includes:
- manage command to be run as a frequent cron job so that we don't have to wait for push to github in the signal handler
- logic to clean up obsolete files when annotations are deleted

sync transcription signal

---

geniza/corpus/annotation_export.py
geniza/corpus/management/commands/tei_to_annotation.py
geniza/corpus/tests/test_annotation_export.py

this PR revises the directory layout for the transcription export, per conversation on https://github.com/Princeton-CDH/geniza/issues/912
here's an example of the previous directory structure:
https://github.com/Princeton-CDH/test-pgp-annotations/tree/test-tei-migration
and here is an example of what the new structure will look like:
https://github.com/Princeton-CDH/test-pgp-annotations/tree/rsk-dev2
(I only tested a few records, and it looks like I tested before I added leading zeros to make the top-level directories 5 digits)

Revise transcription export directory layout

---

geniza/corpus/views.py
package-lock.json
package.json
sitemedia/js/controllers/annotation_controller.js

- Per #1123:
- Pass secondary motivation to tahqiq storage plugin
- Bump tahqiq commit hash
Note: can bump tahqiq commit hash again, to the merge commit after https://github.com/Princeton-CDH/annotorious-tahqiq/pull/18 is merged, if we want to keep it on the `develop` branch

Add secondary motivation to & bump tahqiq (#1123)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
package-lock.json
package.json
sitemedia/js/controllers/iiif_controller.js
sitemedia/scss/components/_annotation.scss

- Per #1131:
- Left-align help text, update to include instructions about pan/zoom and reordering
- Per #1132:
- Add navigator to OpenSeadragon when in edit mode
- Bump annotorious-tahqiq commit hash
- Bump Annotorious to 2.7.8
- Reduce help text opacity (not sure if desired/needed but it seems less distracting this way)

Update editor help text and add navigator to OSD (#1131, #1132)

---

DEPLOYNOTES.md
geniza/context_processors.py
geniza/settings/local_settings.py.sample
geniza/templates/admin/base_site.html
geniza/templates/base.html
geniza/templates/robots.txt
geniza/templates/snippets/test_banner.html
sitemedia/css/test-banner.css
sitemedia/js/main.js

- Per #1150:
- Restore test banner JS and update CSS (replace unused font; `max-width` and padding on `p` prevent viewport overflow issue)
- Make test banner body/header text configurable
- Use feature flag string instead of boolean
- Do the config options need any documentation beyond just being present with comments in `local_settings.py.sample`? (e.g. deploy notes)

Restore test banner and make configurable (#1150)

---

geniza/corpus/admin.py

This should be a fix for issue #883.
Switching join string from ';' to '; ' within fields of CSV export.
Currently the fix does this for all fields (IMO this looks cleaner and is more consistent) and not only the "iiif_urls" field.
The code also switches a few list comprehensions to safer (checks against empty strings) and generator version.

Fixing semicolon problem in iiif_urls

---

DEPLOYNOTES.md
geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

Solr config changes in this PR:
- new custom field for transcription text, with bigram filter #1174 
- revise boosting for date text #1151 and phrase matches across the board
- natural sorting for shelfmarks #1162

document search improvements

---

geniza/corpus/templates/corpus/document_transcribe.html
package-lock.json
package.json
sitemedia/js/annotation.js
sitemedia/js/controllers/alert_controller.js
sitemedia/scss/annotation.scss
sitemedia/scss/base/_colors.scss
sitemedia/scss/components/_alert.scss

see also https://github.com/Princeton-CDH/annotorious-tahqiq/pull/26
- Per #1176:
- Add a new div for alerts bound to a new stimulus controller
- In the new stimulus controller, listen for `tahqiq-alert` events, in order to populate div with alerts
- Add basic styles for different alert statuses
- Bump tahqiq commit hash
- Please test locally, is the overall look and feel OK?
- Should we add publishing the new tahqiq + bumping the version number in PGP (if applicable) to the release checklist?

Show alert toasts on transcription editor (#1176)

---

geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
geniza/templates/footer.html
sitemedia/scss/components/_footer.scss

- Per #1195:
- Add ISSN to footer, matching S&co styles
- Fix resulting lighthouse issue
- Does ISSN need a translation? (I assumed yes!)
- To match the S&Co site I needed to make a few other changes to the layout. Can you [take a quick look at Percy](https://percy.io/2cf28a24/geniza/builds/22188898/), and see if the change is acceptable?

Add ISSN to footer (#1195)

---

geniza/corpus/templates/corpus/snippets/document_result.html
sitemedia/css/admin-local.css
sitemedia/js/annotation.js
sitemedia/js/controllers/alert_controller.js
sitemedia/js/iiif.js
sitemedia/js/main.js
sitemedia/scss/base/_fonts.scss
sitemedia/scss/base/_typography.scss
sitemedia/scss/components/_results.scss
sitemedia/scss/components/_transcription.scss

- Per #1194:
- Apply Arabic type styles, and conditional type styles using inline lang attributes, to transcriptions
- Adjust decimal cover
- Per #1193:
- Apply proper fonts, sizes, line heights, decimal cover to transcription viewer in admin
- Per #1202:
- Add digital edition switcher to admin (move it to `iiif` bundle from `main`)
- Ensure `alert_controller` excluded from `main` bundle (it should only be in `annotation`; this is why I was getting double `connect`s in Stimulus)
- Should this include what we discussed with [`dir` attributes in the HTML](https://www.w3.org/International/questions/qa-html-dir)? If so, should I just apply RTL to all transcriptions for now, or do we want logic to determine it based on language direction?

Transcription styles (#1194) and admin fixes (#1193, #1202)

---

geniza/common/metadata_export.py
geniza/common/tests.py
geniza/corpus/metadata_export.py
geniza/corpus/models.py

@quadrismegistus check it out! I was able to improve the prefetching and the export is much faster now.
It was easier to investigate now that we have a script export — I turned on django logging so I could see db calls,  added a 1s sleep so I could see what was going on, and used that to make sure all the db calls were made at the beginning and none per individual document.  Now the script to export all documents completes in around a minute.

Improve document metadata export speed

---

geniza/common/metadata_export.py
geniza/common/tests.py
geniza/footnotes/admin.py
geniza/footnotes/metadata_export.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_admin.py

same thing as what I just did for sources, I refactored the old tabular_export to use our new metadata export code
I also removed the sorting from the common metadata export serialization code — there are cases where the order may be meaningful and order shouldn't be changed.
FYI, I think both of these will need public variants — we don't want to include the admin url in our public exports, but it's useful for the admin downloads.

Refactor footnote export to use new exporter code

---

geniza/common/metadata_export.py
geniza/corpus/tests/test_metadata_export.py
geniza/footnotes/admin.py
geniza/footnotes/metadata_export.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_metadata_export.py
geniza/footnotes/tests/test_footnote_models.py

Splits out admin and public versions of source and footnote exporter
- makes the base exporter the public versions (for use in metadata export script)
- create admin variants that add admin url
- use admin exporter for admin csv export functionality
- unit tests for the changes
#1100 - updates for footnote export based on problems found in testing:
- `content_text` was returning text `None` when there was no content
- added UTF-8 byte order mark at beginning of CSV so that Excel will read content correctly

Separate admin and public exports for sources and footnotes

---

geniza/common/admin.py
geniza/common/metadata_export.py
geniza/common/templates/admin/admin/logentry/change_list_object_tools.html
geniza/common/tests.py
geniza/corpus/management/commands/convert_dates.py
geniza/corpus/tests/test_convert_dates.py

Quick admin-only csv export for log entries (not intended for inclusion in metadata exports)
I remembered I had a gist from when I've done this in the past as a one-off: https://gist.github.com/rlskoeser/f9312d27eef352e16ccfa25a31132ca5
Adapted that to our new exporter code and tweaked the logentry admin we're using to add it.

Admin LogEntry csv export #918

---

.zenodo.json
CITATION.cff
README.rst

I've turned on Zenodo sync and tagged a release, which created a DOI for the codebase.
In this update:
- add DOI badge to readme
- add zenodo metadata file with information I added to the DOI record, for inclusion in future releases
- add CITATION.cff with the same information, to make easily citable on GitHub

doi + citation file

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/scss/components/_transcription.scss

ref #1216 
- explicitly set text direction for transcription labels
- set text direction in html for transcription block in itt panel, for consistency with search results

address transcription label text direction

---

geniza/corpus/templates/admin/corpus/document/change_form.html

Per #1253:
- Remove conditional that checked for images or transcriptions in order to show the ITT panel, and thus allow adding transcriptions. This conditional prevented users from seeing an "add transcription" link when there was no image or transcription on the document.

Remove transcription/images check for IIT panel in doc admin (#1253)

---

geniza/corpus/admin.py

Per #935:
- In `DocumentTextBlockInline`, instead of using `extra = 1`, use `min_num = 1` and `extra = 0` to show one TextBlock inline form field. This causes an error to appear when saving the record without attaching a fragment.
Note that it's technically still possible to have a document without a fragment, but one has to attach a fragment first and then manually remove it to achieve that state.

Show an error on saving a new document without a fragment (#935)

---

requirements/scripts.txt
scripts/README.md
scripts/jrl_iiif.py

Per #1288 
- Use `row.sequence` to find the second image in each set from JRL IIIF, and ensure that its label reads "verso" and not "recto"
- Is there a way to test this locally, and what settings should I use to do so?
- When this is ready to go, can you help me walk through the steps to run this script on the server and deploy? I imagine it's similar to what we did with the IIIF CSV import, but since it involves the extra step of publishing to GitHub (and it involves existing records) I want to make sure I don't mess it up.

Ensure 2nd image in JRL IIIF is always "verso"

---

geniza/corpus/models.py

Per #1295:
- Fixes issue where sometimes deselected fragment images would still appear as part of the document in the admin
After some debugging, I figured out that the exclusions were only failing when there were _no_ selected images in a given `TextBlock`. Seems like the code I removed is a vestigial check from back when `TextBlock.side` was an actual property and not something computed based on `selected_images`—[this is the oldest code I could find](https://github.com/Princeton-CDH/geniza/blame/ee6d8d1e0fb377fe7168e92ef9983da82b6ace28/geniza/corpus/models.py#L624) with this check.
Unit tests are all still passing, and the admin and public images seem to be working as expected, but maybe I'm missing something. Wish I had documented why I was not counting exclusion unless `b.side` was …

Ignore TextBlock side info when excluding images (#1295)

---

geniza/footnotes/admin.py
geniza/footnotes/tests/test_footnote_admin.py

Per https://github.com/Princeton-CDH/geniza/issues/1252#issuecomment-1382314066:
- Raise validation errors in the `clean` methods of footnote admin inlines and the single footnote admin form, if there are multiple digital editions on the same source/document. Fixes issue where it would just throw a DB integrity error due to the uniqueness constraint violation, and present the user with an opaque 500 error.
It's pretty annoying that DB integrity errors don't automatically generate validation errors! 
Also realized I did a lot of extra work for something that wasn't necessary: validating on deletion of footnotes from the Source admin. You can't even do that in the first place! 🤦 
I was originally planning on making this a hotfix (thought showing an error would be simple!), but I think the …

Display proper validation errors on duplicate digital editions (#1252)

---

geniza/corpus/models.py

Applying this hotfix based on conversation in #1302, in order to unblock testing other things on QA (as transcriptions were failing to show up due to images not being selected). Possibly temporary until that is resolved. See also #1295

Consider all TextBlock images selected when there are 0 selected (#1295)

---

geniza/common/admin.py
geniza/common/tests.py
geniza/corpus/forms.py
geniza/corpus/templates/admin/corpus/tag/merge.html
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_forms.py
geniza/corpus/views.py

Per #506:
- Add feature to tag admin allowing admins to merge several tags into one primary tag
- This may not be entirely DRY, considering how much was cribbed from the document merge feature, but it seems like there is just enough variance in each method that it might not be straightforward to generalize. Is this repetitive enough that it's worth the time to generalize? (I guess one reason to do so would be if there are other kinds of merges they will need to do in the future, but I'm not sure there are.)
- Do you think it's ok to not require a rationale here? I think tag merges are pretty straightforward and less impactful so I didn't think it was necessary.

Add tag merge feature (#506)

---

geniza/annotations/tests/test_annotations_models.py
geniza/annotations/tests/test_annotations_views.py
geniza/annotations/views.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_signals.py

Per #1308:
- On annotation update, wait until after annotation's `save()` method is called to reindex associated document, to ensure latest revision is in index
- On annotation creation, reindex associated document

Reindex annotated documents after annotation save, on update and create (#1308)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
sitemedia/scss/components/_transcription.scss

Per #1229:
- Revise `DocumentTranscribeView` placeholder image logic to include exactly two placeholders for each fragment without images in the transcription editor, so that joins with multiple fragments will show enough placeholders to add all transcription content
Per #1230:
- On placeholder images, show labels with each associated fragment's shelfmark (and recto/verso for 1st and 2nd image)
- Include TextBlock id in placeholder canvas URI
- Revise `Document.iiif_images` to look for that TextBlock id and associate the placeholders with the correct shelfmark labels
I think the method of using the TextBlock id in the placeholder URI is a little bit hacky, but it seems to work. My thinking was that this way, if images get added after transcriptions, the placeholder images will still show …

Add placeholders with labels for imageless fragments (#1229, #1230)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/annotation_controller.js
sitemedia/scss/components/_annotation.scss
sitemedia/scss/components/_transcription.scss

Per #1261:
- Allows users to "stick" an image to the left side of the screen in order to continue transcribing when the transcription extends past the visible portion of the image
I spent a lot of time trying to get `position: sticky` to work, or mimic that behavior with JS, but I wasn't able to get it to work with the current HTML/CSS structure. In order to avoid making significant changes, I came up with a compromise: a "pop out" button that only appears in the editor, which takes up half of your screen with the image, in a fixed position.
It's not the best looking thing in the world, but it's just for the editor, and seems to work OK.
Would appreciate a checkout and test locally if you have the time!
(Also, the html changes aren't that significant; recommend hiding whitespace changes …

Add "pop out" button to images in editor (#1261)

---

geniza/corpus/forms.py

Per #1316:
- Use `gettext_lazy` instead of `gettext`, which is required for forms to be translated according to [django docs](https://docs.djangoproject.com/en/4.1/topics/i18n/translation/#lazy-translation), on search form

Use gettext_lazy for search form per django docs (#1316)

---

scripts/README.md
scripts/bodleian_iiif.py
scripts/gen_ptiffs.py
scripts/manifests_to_csv.py

Per #1198, revise Bodleian IIIF script to:
- Split multi-folio manuscript parts into individual shelfmarks per folio, using numeric ranges from `<locus>` nodes (will disregard `<msPart>` numbering)
- Locate folio/image ranges for manuscripts without `<msPart>`
- Handle idiosyncratic image filenames, and a couple of other edge cases
- Remove some unused imports
- Create grouping directories if they do not exist
---
- I successfully completed the image downloads for all manuscripts, except where noted below. Once this PR is approved, I'll follow the next steps: converting the pyramidal tiffs and uploading them, then re-running this script to produce manifests.
- Make sure to turn off whitespace differences in the diff view!
Additionally, here are some types of idiosyncrasies I ran into, and …

Revise bodleian_iiif.py to fix shelfmark sequences and other idiosyncrasies (#1198)

---

sitemedia/css/admin-local.css

Per #1338:
- A bit of admin CSS to manually override the document date section to display as a grid, with a gap wide enough to accommodate the help text issue
- Help text issue was happening because the field label is more than one line long and pushing down the help text, which we can't otherwise address without changing the HTML structure (or doing hacky negative margin stuff)

Improve help text display for document admin date (#1338)

---

geniza/common/admin.py
geniza/common/tests.py

Per #1333:
- Validate tag names are unique, case-insensitive, during create or update of a tag within the tags admin

Add case-insensitive unique validation to tag name field (#1333)

---

scripts/count_transcriptions.bash

Adds the bash script I adapted for counting number of transcriptions over time in the pgp-text repo

Bash script to count number of transcriptions in pgp-text repo

---

geniza/corpus/dates.py
geniza/corpus/management/commands/convert_dates.py
geniza/corpus/tests/test_dates.py

Per #886, support automatic conversion of Seleucid dates to CE.
Had the scholars check [the report](https://docs.google.com/spreadsheets/d/1ccEIstQVp6yDxLsagVqHmPW-7m0YpYvbrK7BWoQ0yYY/edit), and they also passed it along to some outside researchers; all agreed the conversions were sound. They also requested that all existing standard dates be updated using the new formula, so I'll run `convert_dates update` after this is merged.
Do you think we should add an option to `convert_dates` to only update a certain calendar, or should it be fine to just go ahead and update all of them?

Seleucid dates (#886)

---

geniza/annotations/tests/test_annotations_views.py
geniza/annotations/views.py
geniza/corpus/annotation_export.py

Per #1357:
- Fix bug where only `DIGITAL_EDITION` was getting removed when all annotations were deleted (even when the footnote didn't have that relation!)
- Fix export bug where `outfile.write(None)` could get called, likely as a result of the previous error (annotation was not deleted correctly); in case it happens again, handle this gracefully in export

Fix bugs with delete/empty annotation (#1357)

---

geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/iiif_controller.js
sitemedia/js/controllers/ittpanel_controller.js
sitemedia/scss/components/_transcription.scss

- Per #1413, allow users to expand images to reach nearly the full width of the window, on desktop, when only images are visible; and toggle to collapse
- Fix some null checks in the Stimulus controller for ITT panel toggles when transcription or translation are not present

Add "enlarge image" button when only image visible (#1413)

---

geniza/corpus/admin.py
geniza/corpus/tests/test_corpus_admin.py

Per #1384:
- Adds two convenience filters to the Document admin list view for finding translations specifically in Hebrew or English.

Add English, Hebrew translation filters to admin (#1384)

---

geniza/corpus/templatetags/admin_extras.py
geniza/corpus/tests/test_corpus_templatetags.py

Changes from [later commits on the adapted codebase](https://github.com/dezede/dezede/commits/a76c6792a44e3531dd3dcc01925db703567307b5/libretto/templatetags/admin_extras.py) already fix this bug, thankfully! This PR simply implements them.

Respect perms in mixed inlines/formsets (#1434)

---

geniza/entities/admin.py
geniza/entities/tests/test_entities_admin.py

Per https://github.com/Princeton-CDH/geniza/issues/1366#issuecomment-1672467994:
- When adding a new person, the most recently edited (existing) person would not appear in the Person-Person autocomplete list, making the relationship impossible to add. This was caused by a bug where the previous `PersonAdmin.own_pk` was persisted when a new person was being added.
- This PR fixes that bug

Reset entities person admin own_pk to None on add (#1366)

---

geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py

Per #1438:
- Add `order_by("content__schema:position", "created")` to the annotation set in `Footnote.content_html`, so that reordered annotations will appear in the correct order on the document detail page
- Since this is a cached property, I'm wondering about cache busting when annotations are reordered. It seems to work for me locally when I hard refresh the doc detail page, but wondering if that's always the case / if there's a way to do it automatically from the backend?

Respect annotation reordering in document detail page (#1438)

---

sitemedia/css/admin-local.css
sitemedia/js/controllers/ittpanel_controller.js
sitemedia/scss/components/_transcription.scss

Per #1409:
- Fix issue where alignment was only applied to the first transcription/translation block, and only the first OL within those
- Also apply this fix to alignment removal
- Fix issue where `min-height` was sometimes causing misalignment due to lack of `max-height`
- Fix issue where initial OL alignment for translation was exactly 1 pixel off
- Fix django admin CSS conflict issues
Per #1431:
- Apply alignment removal and re-alignment on window resize (if on desktop and both transcription and translation are open)
Other:
- I noticed the "li period hider" element was sometimes misaligned in various configurations, so I adjusted it in both the public and admin CSS

Various alignment bugfixes (#1409, #1431)

---

geniza/corpus/templates/corpus/document_scholarship.html
geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_templatetags.py

per #1446:
- Use template filter to check if any footnote on a source has a location or url
- Use template filter to collect doc relations for ALL footnotes on the source, not just displaying the first

Fix display of multiple footnotes on same source (#1446)

---

geniza/context_processors.py
geniza/templates/base.html
sitemedia/js/controllers/theme_controller.js

Per #1437
- Disable turbo on any request where the user agent includes `archive.org_bot`
- Adds the ability to append `?dark-mode=true` to any url to force dark mode

Improvements for web archiving (#1437)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

Per #887:
- Use `Document.created` as a fallback when indexing input date, if the document's initial log entry is not yet created
- Using the query from your comment in the issue, I found 364 documents on the public site that were missing input dates in the index, so it's definitely a common issue. (I also reindexed those documents on the public site so they are all fixed now.) But I think you are right that this will resolve it for all new records, which seems to be the only case where it happens anyway.

Use Document.created as fallback input date in index (#887)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py

Per #1429:
- In document merge, handle dates
- Raise ValidationError on conflicting standard/original document dates
- If not in conflict, ensure no standard/original document dates are lost during merge
- Add all inferred datings from merged documents

Resolve document and inferred dates in document merge (#1429)

---

geniza/entities/admin.py
geniza/entities/tests/test_entities_admin.py

Per #1461:
- Simply add "document" as an autocomplete field on Person and Place Document inlines
- Also remove `document_link` as it won't be needed
it searches on the string representation, and it seems fast enough. If there are issues we can revise.

Allow adding document directly to entity using shelfmark/PGPID search (#1461)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_admin.py

Per #1483
- Set `q.op=AND` in `admin_doc_qf` to replace `mm=100%`, so that the `AND` boolean applies by default but can be overridden by specifying `OR` in the search query text

Set q.op=AND for admin doc search (#1483)

---

geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_solrqueryset.py

Realized while writing testing notes for #1070 that rotated images did not appear in search results. So I made the following changes:
- Index rotation overrides as `*_is`, and zip into tuples in `get_result_document`, following the same pattern as labels
- Fallback to list of 0s (the same length of the list of images)
- Display rotated images in results using same method from ITT viewer
The nice thing about the fallback is that we don't have to reindex anything manually, as we know rotation is always 0 unless the override has been set, at which point the document will reindex on save.

Index rotations and display in search results (#1070)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/entities/models.py
geniza/entities/tests/test_entities_models.py

Per #1506:
- Allow a document or person to be merged into a document or person that does not have a description

Allow merge into primaries with no description (#1506)

---

geniza/corpus/templates/corpus/document_list.html
geniza/corpus/templates/corpus/snippets/document_transcription.html
lighthouserc.js
sitemedia/js/controllers/ittpanel_controller.js
sitemedia/scss/components/_searchform.scss

Per #1505
- Fix an issue where multiple transcriptions/translations would not be handled correctly by the stimulus controller:
- The transcription/translation targets that were being aligned were not only the currently selected, but a mix of chunks from selected and unselected ones
- Changing the currently selected transcription or translation would not trigger a realignment
- Alignment failed to reset inline padding on tops of lists when necessary

Fix broken alignment for multiple transcriptions/translations (#1505)

---

geniza/corpus/tests/test_corpus_views.py
solr_conf/conf/solrconfig.xml

Per #1335:
- Boost exact matches in description (`content_nostem`) above partial matches in shelfmark
- Boost exact matches in shelfmark (`shelfmark_s`) above both

Improve boosts for description exact matches (#1335)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py

Per #1476:
- Add a new `uf` param to searches that contain nested `type=edismax` searches, as [since solr 7.2](https://solr.apache.org/guide/7_2/solr-upgrade-notes.html#solr-7-2) they will not work without it. (Shelfmark scoped search happened to be the one place where a `type=edismax` exists inside another `type=edismax` so far!)

Allow deprecated edismax nested search for shelfmarks (#1476)

---

geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py

Per #1275:
- When choosing a source, search based on a combination of all authors, title, and volume

Allow source autocomplete on combined author and title (#1275)

---

DEPLOYNOTES.md
geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_views.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

Per #1286:
- Allow searching for exact matches on words with brackets and other [transcription sigla](https://docs.google.com/document/d/1pyFajrGRYTzRsb2yFjfX0XmNqpz1kUO9mhlISGwfpxk/edit) inside them using double quotes (e.g. `"wo[r]d"` should match a transcription with `wo[r]d` in it verbatim)
- Use whitespace tokenizer instead of standard tokenizer in transcription field to prevent sigla from breaking up words
- Exclude double quoted exact searches from arabic-JA conversion
- Allow searches for words without sigla to match instances of the word with sigla inside, when not using double quotes (e.g. `word` should also match a transcription with `wo[r]d` in it)
- Use a transcription cleaning method to index such words

Allow searching for words with brackets and other sigla in transcriptions (#1286)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/footnotes/models.py
geniza/footnotes/tests/test_footnote_models.py
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

As you suggested @rlskoeser, moving the regex to solr was absolutely the way to go here! Not only did it simplify the indexing code and reduce the index size, but it also fixed a bug where a search term without sigla would not be highlighted in a transcription where that term only appears _with_ sigla.

Migrate regex from python to solr (#1286)

---

geniza/entities/admin.py
geniza/entities/tests/test_entities_admin.py
geniza/entities/tests/test_entities_views.py
geniza/entities/views.py

Per #1479:
- Allow diacritic-insensitive search in People and Places admin list views (not just autocomplete)
- Update autocomplete for both to also allow matches in `names__name`; in other words, allow users to type diacritics in the autocomplete

Allow diacritic-insensitive searching in admin list views for People/Places (#1479)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

Per #1570:
- Index and store nostem fields
- Split `content_nostem` into `description_nostem` and `transcription_nostem`
- Convert exact searches from scoped `content_nostem:` to `OR` between scoped description/transcription nostem fields
- Highlight new description/transcription nostem fields
- Replace `description` and `transcription` highlights in highlights dict with `description_nostem` and `transcription_nostem` highlights when searching for exact matches

Highlight nostem matches on exact searches (#1570)

---

geniza/corpus/admin.py
geniza/corpus/forms.py
geniza/corpus/tests/test_corpus_admin.py
geniza/entities/admin.py
geniza/entities/tests/test_entities_admin.py

Per https://github.com/Princeton-CDH/geniza/issues/1512#issuecomment-2043959712:
- Allow adding a new Event from a Person page via popup
- Add a new `from_document=true` URL param to the related widget wrapper "add new Event" button
- Change `EventDocumentInline.get_min_num` behavior such that `min_num` of associated Documents required for a new Event is zero _only_ when the `from_document` param is present, and not just when the `_popup` param is present (as that can now happen via popups launched from Person pages too)

Allow adding new events from Person form (#1512)

---

geniza/entities/forms.py
geniza/entities/tests/test_entities_forms.py
geniza/entities/views.py

Consider filters to be active if a sort is applied, as otherwise facet counts are inaccurate.

Fix bug with facet counts after sorting (people list view)

---

geniza/corpus/models.py
geniza/corpus/solr_queryset.py

Prevents a lot of extra solr queries during search; possibly at the expense of some indexing time.

Index related document counts instead of computing them on the fly

---

geniza/entities/models.py
geniza/entities/templates/entities/person_list.html
geniza/entities/tests/test_entities_models.py
geniza/entities/tests/test_entities_views.py
geniza/entities/views.py
sitemedia/scss/components/_peopleform.scss

Allows people range stats to populate correctly, prevents visual overflow of date range filter in panel

Use new property names for range stats on people list

---

geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_solrqueryset.py
solr_conf/conf/solrconfig.xml

- When a search term is entered that is only a shelfmark-scoped phrase in quotes, handle differently from normal searches.
- This is needed due to the nested edismax query issues: it starts applying the other words in the shelfmark quoted phrase to the other query fields. This is fine in searches on more than just shelfmark, but produces unexpected results when searching only on shelfmark.
- Fix issue with old shelfmark appearance in search results
- Add old_shelfmark to fields to shelfmark_qf

Handle shelfmark-only search, improve old shelfmark boost (#1469)

---

geniza/corpus/forms.py
geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/document_list.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_forms.py
geniza/corpus/views.py
sitemedia/js/controllers/search_controller.js
sitemedia/scss/components/_searchform.scss

Per #1402:
- Index all languages of translation footnotes (by name) per document
- Add `Select` facet filter form field type
- Use that facet to select languages of translation
- Disable form control unless "has translation" is checked

Add language facet filter to document search (#1402)

---

geniza/entities/templates/entities/person_detail.html
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/pages/_person.scss

Per #1649:
- Include document links under descriptions in the events timeline on person detail page
- Ensure this layout works on RTL
Unrelated, but also compiles translation messages.

Include document links in event timeline (#1649)

---

geniza/entities/metadata_export.py
geniza/entities/tests/test_entities_admin.py
geniza/entities/tests/test_entities_metadata_export.py

Per #1641:
- In related objects CSVs: Include a column `source_place` or `source_person` in order to include the name of the record that all related objects are associated with.

Include source record name in relations CSVs (#1641)

---

geniza/corpus/models.py
geniza/corpus/templates/corpus/document_detail.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_templates.py
sitemedia/scss/pages/_person.scss

Per #1668:
- Add citation following the given format to the bottom of document detail pages
- Remove unit tests for "editors" information in document detail metadata sections

Add citations to the bottom of document detail pages (#1668)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_views.py

Per #1582:
- In general search, check entered query for any of the list of Hebrew prefixes (ו ל ב כ מ ה שׁ פ אל)
- If one matches, search that word with or without the prefix, as an OR query

Search prefixed Hebrew words, return non-prefixed versions (#1582)

---

geniza/corpus/ja.py
geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_ja.py

Per #1679:
- Add table and functions to convert from Judaeo-Arabic (Hebrew script) to Arabic
- Apply these to any search that contains Hebrew characters
- Make translingual conversion function generic so that it can be used in either direction

Allow searching JA to return Arabic results (#1679)

---

geniza/corpus/ja.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_ja.py

Per https://github.com/Princeton-CDH/geniza/issues/1679#issuecomment-2510415548:
- Improve original language boosting across the board
- Also revert the style back to using the pipe operator instead of `OR`

Improve original language boost for translingual search (#1679)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

Per #1674:
- Always order listed collections by shelfmark order (i.e. `TextBlock.order` property) rather than alphabetically

Order list of collections by textblock order (#1674)

---

geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py

Per #1674:
- Uses list instead of set for collections, as the required order cannot be maintained with set

Ensure order of collection objects is correct (#1674)

---

geniza/corpus/ja.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_ja.py

Per #1679:
- Set back to `OR` instead of `|`. The pipe was causing results to be excluded incorrectly.
- Increase boost from 5 to 100 for original language. Otherwise, `OR` seemed to cause relevance scores to be higher at times for the transliterated language.

Translingual search: use OR; increase boost (#1679)

---

geniza/corpus/management/commands/escr_alto_to_annotation.py

Per #1685:
- Update the ingest script to use xywh FragmentSelectors for Weiss. We don't actually want to preserve its block-level geometry, and its presence was causing server errors.

Use xywh FragmentSelector for Weiss (#1685)

---

.github/workflows/visual_tests.yml
geniza/entities/forms.py

also turn off percy unless asked for specifically, since it's now saying there are changes every time we commit on a new date (due to the dated citation at the bottom of doc detail pages)

Add help text to person-person field to avoid relationship dupes (#1639)

---

geniza/common/admin.py
geniza/corpus/admin.py
geniza/entities/admin.py

Per #1688:
- Create a new `TypedRelationInline` mixin for relationships that have a "type" field, with an overridden `get_formset` method to remove the "delete" button for that type field
- This is to prevent inadvertently deleting the entire type, rather than just the relationship. The delete button does not need to be here, a type should be deleted from its own model page in the admin
- Do the same for "language" on Name, for the same reason

Remove delete butons from "type" fields in relation inlines (#1688)

---

sitemedia/js/controllers/ittpanel_controller.js

Per #1698:
- Fix a bug where the transcription/translation "chunks" were being counted differently during editing, thus leading to mismatches when trying to align the two

Fix transcription/translation alignment during editing (#1698)

---

sitemedia/js/controllers/ittpanel_controller.js
sitemedia/scss/components/_transcription.scss

Per #1698:
- ensure re-alignment on annotation load in the editor
- a small css tweak for double digit ltr line numbers

Improve alignment behavior in editor (#1698)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py

Per #1710:
- Prevent whitespace from being added around highlights in regex search, by not running `clean_html` on regex search
`clean_html` is not useful for regex search since the only html there will be `<em>` tags.  We don't need to worry about malformed HTML there; and `clean_html` will try to add `\n` around `<em>` tags because it is a prettifier.

Prevent whitespace from being added around highlights in regex search (#1710)

---

geniza/entities/forms.py
geniza/entities/models.py
geniza/entities/templates/entities/person_list.html
geniza/entities/tests/test_entities_models.py
geniza/entities/tests/test_entities_views.py
geniza/entities/views.py
sitemedia/js/controllers/search_controller.js
sitemedia/scss/components/_peopleform.scss
sitemedia/scss/components/_searchform.scss
sitemedia/scss/pages/_people.scss
sitemedia/scss/pages/_search.scss
solr_conf/conf/managed-schema
solr_conf/conf/solrconfig.xml

Per #1711:
- Allow public users to search on people's names
- Searches primary names and secondary names
- Primary names get priority; secondary names included in highlights so that they will show up in search results
- Name fields analyzed by a couple of different analyzers (bigram for basic search, nostem for exact matches)
- Selects/deselects "relevance descending" sort automatically using the radio button elements based on whether or not a keyword query is entered

Add keyword search on people's names (#1711)

---

geniza/corpus/templates/corpus/document_list.html
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py
sitemedia/scss/components/_results.scss

Per #1697:
- Generate a link to the Arabic Papyrology Database when Arabic or JA are entered in the document search query
- Generate a regex version of a JA-to-Arabic translation for this link, since APD is only in Arabic, and supports regex
- Show the link at the bottom of the search results if it exists

Add APD link to doc search on Arabic/JA query (#1697)

---

.github/workflows/sphinx_docs.yml
.github/workflows/unit_tests.yml
.github/workflows/visual_tests.yml
geniza/corpus/templates/corpus/snippets/document_transcription.html
sitemedia/js/controllers/ittpanel_controller.js
sitemedia/scss/components/_transcription.scss

Per #1680:
- Add a short 50ms timeout before starting alignment in order to fix alignment on Chrome and Firefox at non-100% zoom levels (delaying bounding box calculations this amount seems to always result in the correct dimensions)
- For Safari, calculate the window's pixel zoom ratio using `window.outerWidth / window.innerWidth` and apply the ratio accordingly to bounding box calculations (this _doesn't_ work in Chrome/Firefox)
- Also, because we now have translation lines that will sometimes be upwards of 20 lines long (after wrapping at 125% zoom), programmatically generate up to 30 lines worth of CSS line height rules using SCSS `@for`

Adjust alignment for non-100% zoom levels (#1680)

---

geniza/entities/admin.py
geniza/entities/forms.py
geniza/entities/tests/test_entities_admin.py
geniza/entities/tests/test_entities_views.py
geniza/entities/views.py

Per #1731:
- Allow tag search in admin by using solr query when searching for people in the admin
Other:
- Fix broken autocomplete on person-person relations. There was a bug in `PersonAdmin.get_queryset` that was meant to exclude the parent person from autocomplete when related people were being added—in other words, to prevent a person from being added as a related person to itself. The autocomplete view's `get_queryset` method was called instead of `PersonAdmin.get_queryset`, so logic there was ignored. This PR uses slightly different logic to achieve the same ends, using `django-autocomplete-light`'s `forward` function and URL parsing to determine when and which person to exclude.

Allow tag search in admin (#1731)

---

geniza/annotations/models.py
geniza/corpus/views.py
package-lock.json
package.json
sitemedia/js/controllers/annotation_controller.js

Per #1617:
- Update `annotorious-tahqiq` and use its new config option to enable italics, only on the translation editor
- Whitelist the resulting `em` tags in the annotation cleaning logic

Allow use of italics in translation editor (#1617)

---

geniza/annotations/models.py
package-lock.json
package.json
sitemedia/scss/base/_global.scss

Solr uses `em` elements to highlight search results, which was conflicting with #1617 where we added the option to italicize words with `em` tags in the `annotorious-tahqiq` editor.
This PR bumps tahqiq to the new version that uses `i` tags instead, which is more semantically accurate as well, and whitelists `i` tags while removing `em` from the whitelist. It also adds styling to the `i` tag to show it as italic.

Resolve em conflict with highlight (#1617)

---

geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_templates.py
geniza/corpus/tests/test_corpus_views.py
sitemedia/scss/components/_results.scss

Per #1700:
- Because regex results show all matches across a document's transcription content, the snippets can come from multiple transcription sources. So:
- Index source labels alongside every transcription snippet. The labels are indexed separately but in the same order, and solr multivalued field order is predictable and persistent.
- In regex search, match each highlighted snippet with its source label, and display them both on the result.
- Ensure a source label is only shown once per transcription.
Unrelated:
- Fix a bug where at least one word was required to be both before and after a match in a regex-matched text in order for highlighting to work. In other words, a word that appeared at the very beginning or end of a transcription would not be highlighted. This was part of the …

Show sources of snippets in RegEx search results (#1700)

---

geniza/corpus/tests/test_corpus_views.py
geniza/corpus/views.py

Per #1752:
- Use shelfmark sort as a secondary sort; useful for tiebreaking relevance scores, such as in tag search where relevance scores are often identical

Use shelfmark as tiebreaker for score sort (#1752)

---

sitemedia/scss/components/_results.scss

Per #1700:
- Fix a bug where space was being inserted with CSS incorrectly on regex highlights
Due to the way solr highlights adjacent word matches, spaces were being intentionally inserted with CSS after the fact. This works fine for solr highlights, but was causing problems with our manual regex highlights, where there would be multiple matches in a snippet, with text nodes between them. An example scenario:
Indexed content: "Example phrase"
> General search: `Example phrase`
> Solr highlight: `<em>Example</em><em>phrase</em>`
> Appearance with CSS space rule (`em + em` matches): **Example phrase**
> Regex search: `Example phrase`
> Manual highlight: `<em>Example phrase</em>`
> Appearance with CSS space rule (`em + em` does not match): **Example phrase**
> Regex search: `a`
> Manual …

Only add space between em elements in non-regex search (#1700)

---

geniza/corpus/views.py
sitemedia/js/controllers/annotation_controller.js

Per #1751:
- In case of institutional outages: Add a handler for OpenSeadragon's `open-failed` event that replaces the failed image with a placeholder, in annotation mode only

Use placeholder for annotation if tileSource fails to load (#1751)

---

geniza/corpus/solr_queryset.py
geniza/corpus/tests/test_corpus_solrqueryset.py
sitemedia/scss/components/_results.scss

Per #1700:
- Fix an issue where `<em>`, `</em>`, and `<br />` could match on the second RegEx pass, breaking the HTML for display
- Fix an issue where two matches could be adjacent and separated by a space, and those `<em>` elements would display without a space between them

Fix two issues with RegEx multi-match (#1700)

---

DEPLOYNOTES.md
geniza/corpus/forms.py
geniza/corpus/models.py
geniza/corpus/solr_queryset.py
geniza/corpus/templates/corpus/document_list.html
geniza/corpus/templates/corpus/snippets/document_result.html
geniza/corpus/tests/test_corpus_models.py
geniza/corpus/tests/test_corpus_solrqueryset.py
geniza/corpus/tests/test_corpus_views.py
geniza/corpus/tests/test_forms.py
geniza/corpus/views.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po
sitemedia/scss/components/_searchform.scss
solr_conf/conf/managed-schema

Per #1755:
- Add shelfmark, description, and translation regex search options
- Refactor regex search functions to be field-agnostic to support those options
- Add a special case to regex search and highlighting to ensure old shelfmarks can match and appear in results
- Restyle with dropdown, add regex search to mobile

Add shelfmark, description, translation regex search options (#1755)

---

geniza/corpus/admin.py

Per #1658:
- Specify field order in the Collection admin, such that it is the same as before, but with `name` before `abbrev`.

Specify collection field order in admin (#1658)

---

sitemedia/scss/base/_fonts.scss

Per #1701:
- Create a new `@font-face` declaration that uses Greta Sans and covers just the Unicode "Basic Latin" block `U+0000-007F`
- Use that font as a fallback for transcriptions, while still allowing non-Latin missing glyphs to use Times New Roman (the other transcriptions fallback font)

GretaSans for Basic Latin in transcription (#1701)

---

package-lock.json
package.json

**Associated Issue(s):** #1482
_Include all key changes in this pull request_
- Upgrade `@hotwired/turbo` to fix an issue where stale page metadata would be persisted across turbo frame loads

Bump @hotwired/turbo to v8.0.13 (#1482)

---

geniza/corpus/admin.py
geniza/corpus/tests/test_corpus_admin.py

**Associated Issue(s):** #1496
- Order the form field dropdown for document type alphabetically

Alphabetize Document type dropdown (#1496)

---

geniza/corpus/models.py
sitemedia/css/admin-local.css
sitemedia/js/admin.js

**Associated Issue(s):** #1598
- Include `selected` information with thumbnails in the rotation/order override section view context
- Allow selection/deselection of images in that section, with selected border display and a checkbox, which synchronizes with the existing fragment-level section

Unify img selection with rotation/order (#1598)

---

geniza/corpus/dates.py
geniza/corpus/models.py
geniza/entities/models.py
geniza/entities/templates/entities/snippets/related_documents_table.html
geniza/entities/tests/test_entities_views.py
geniza/entities/views.py
sitemedia/scss/pages/_related.scss

Per #1781:
- For a Person's (or Place's!) front-end Related Documents page:
- Batch queries for document shelfmarks (`Fragment.shelfmark` related to document by `TextBlock`), dates (`Dating`), types (`DocumentType`), and relationship names (`PersonDocumentRelationType` / `DocumentPlaceRelationType`)
- Make date calculation independent from `Dating` model lookups so that the logic can be used on prefetched records
- Prevent network requests for IIIF manifests during lookups for document thumbnails, so as only to use cached manifests
- Prevent additional query for page description count
- Update template and unit tests to account for changes
- For a Person's main detail page, use `prefetch_related` to batch the queries for document dates, in order to get person's active and deceased dates …

Optimizations for Person "Related Documents" front-end (#1781)

---

sitemedia/scss/components/_navigation.scss

**Associated Issue(s):** #1794
- Edit the `flex-grow`/`flex-shrink` for navbar hover indicators to resolve the issue with wrapping in Chrome

Fix nav hover indicator issue with chrome (#1794)

---

geniza/corpus/metadata_export.py
geniza/corpus/tests/test_metadata_export.py
geniza/footnotes/metadata_export.py
geniza/footnotes/tests/test_footnote_metadata_export.py

**Associated Issue(s):** #1765
- Add `distinct()` call to `PublicFragmentExporter.get_queryset` to dedupe after `documents__status` filter

Prevent dupe fragments in public export (#1765)

---

geniza/entities/views.py
geniza/locale/ar/LC_MESSAGES/django.po
geniza/locale/en/LC_MESSAGES/django.po
geniza/locale/he/LC_MESSAGES/django.po

**Associated Issue(s):** #1781
- Fix an error in person related documents pages, where `None` would break sorting by doctype
- Regenerate translation files

Handle Nones in Person "Related Documents" page doctype sort (#1781)

---

geniza/corpus/admin.py
geniza/corpus/models.py
sitemedia/js/admin.js

**Associated Issue(s):** #1598
- Fix an issue where selection state could be mismatched due to the way `exclude` is computed in `Document.iiif_images`. Instead, use the actual form selection state from the `TextBlock` inlines to determine the selection state for the reorder/rotate field.

Fix possible image selection state mismatch in reorder/rotate field (#1598)

---

geniza/corpus/templates/corpus/document_detail.html

**Associated Issue(s):** #1805
- Use the original design (one-line, non-tabular) for provenance when the document only has one provenance across all fragments

Exempt single-provenance docs from tabular provenance display (#1805)

---

sitemedia/js/admin.js

**Associated Issue(s):** #853 
_Fix the behavior of checkmarks when updating a footnote_
- Changed ul to div in 3 spots
- Only frontend (JS) modifications
The expected behavior is tested

Upgrade bugfix

---

sitemedia/js/controllers/iiif_controller.js

**Associated Issue(s):** #1824
- Use `GET` instead of `HEAD` to check for broken IIIF images in transcription/translation editor
- This fixes a bug where `HEAD` requests to puliiif would return 403 errors, while `GET` requests would succeed. Thus, the image would appear to be broken and use a placeholder, when in fact it was working fine.

Use GET instead of HEAD to check iiif (#1824)

---

geniza/entities/templates/entities/snippets/related_documents_table.html
sitemedia/js/controllers/thumbnail_controller.js

**Associated Issue(s):** #1826
- Attach a new Stimulus controller to document thumbnails in related documents pages, which use `/square/` in IIIF Image v2.1 to create square crops. If the image fails to load, assume it is IIIF v2.0 (like JRL) and attempt to manually create a centered square crop.

Fallback for IIIF Image v2.0 images, such as JRL, to manually create square-cropped thumbnails (#1826)

---

sitemedia/scss/components/_searchform.scss

**Associated Issue(s):** #1836
- Fix positioning issue with the People search page "Exclude Uncertain" toggle present in Firefox and Safari

Fix positioning issue with "exclude uncertain" toggle (#1836)

---

geniza/common/admin.py
geniza/common/signals.py
geniza/corpus/admin.py
geniza/corpus/models.py
geniza/corpus/tests/test_corpus_models.py
geniza/entities/admin.py
geniza/entities/models.py
geniza/entities/tests/test_entities_models.py

**Associated Issue(s):** #1848
- Pull `get_deleted_objects` out of `DocumentAdmin` and make it a generic admin mixin
- Apply it also to `PersonAdmin`, `PersonDocumentRelationTypeAdmin`, and `PersonPersonRelationTypeAdmin`
- This removes log entries from the list of permissions checked / objects listed for deletion, when deleting one of these objects that has a `GenericRelation` to log entries
- Pull `detach_document_logentries` signal handler out of `corpus` and into `common`
- Attach it also to `Person`, `PersonDocumentRelationType`, and `PersonPersonRelationType`
- This detaches log entries from their related objects so that when those objects are deleted, the log entries don't also get deleted

Fix deletion issue with LogEntries (#1848)

---

geniza/entities/admin.py
geniza/entities/tests/test_entities_admin.py

**Associated Issue(s):** #1803
- Prevent deleting a Person record's only display name
- Fix a bug that crashed person admin search when a record was accidentally indexed with no slug

Prevent deleting display name; fix no-slug admin search bug (#1803)

---

geniza/corpus/templates/corpus/document_list.html
sitemedia/scss/components/_navigation.scss
sitemedia/scss/components/_peopleform.scss
sitemedia/scss/pages/_places.scss

**Associated Issue(s):** #1844, #1820, #1790
- Various mobile CSS tweaks:
- Use `dvh` units when available to make map height work on safari ios
- Fix `legend` rendering in form filters
- Fix borders applied to incorrect elements in form filters

Various mobile CSS tweaks (#1844)

---

geniza/corpus/forms.py
geniza/corpus/models.py
geniza/corpus/templates/corpus/snippets/document_option_label.html
geniza/corpus/tests/test_corpus_models.py
geniza/entities/models.py
geniza/entities/templates/entities/snippets/person_option_label.html
geniza/entities/tests/test_entities_models.py
sitemedia/css/admin-local.css

**Associated Issue(s):** #1854
- Ensure relationships to entities (person/place/event), and description authorships, aren't clobbered in Document merge
- Show them in the table in the merge template
- Create a reusable helper function to merge Document related records
- Ensure no duplicate relationships are created (i.e. same Person + Type on Document, same Place + Type on Document, same Event on Document)
- In the case of a duplicate being found, ensure all notes are combined on the primary document
- Refactor Person merge, ensure related events not clobbered by merge
- Fix bug with Social Roles in the merge template
- Create a reusable helper function to merge Person related records
- Add some special handling for Person-Person relationships (asymmetrical self-referential M2M)
- Update …

Ensure all related records merged in document and person merges (#1854)

---

geniza/annotations/models.py
geniza/annotations/tests/test_annotations_models.py

**Associated Issue(s):** #1801
- Adding a method to flatten nested lists into a single list while preserving all items and sub-items
- Adding a test case

#1801 Flattening nested lists while preserving all items and subitems when adding/editing transcription/translation

---

geniza/entities/admin.py
geniza/footnotes/admin.py
geniza/settings/components/base.py
pyproject.toml

**Associated Issue(s):** #1783
Per #1783:
- Prevent massive slowdown on Person admin edit pages with many relationships, such as Nahray b. Nissim, by paginating queries to related documents and related people
- Upgrade the no longer maintained `django_admin_inline_paginator` to its active replacement fork, `django_admin_inline_paginator_plus`

Paginate person-document, person-person inlines (#1783)

---

geniza/corpus/templatetags/corpus_extras.py
geniza/corpus/tests/test_corpus_templatetags.py
geniza/footnotes/models.py

**Associated Issue(s):** #1800
Per #1800:
- Prevent empty `doc_relation` on Footnotes from being displayed in and below citations

Prevent empty doc relation from displaying (#1800)

---

sitemedia/scss/components/_transcription.scss

**Associated Issue(s):** #1408
Per #1408:
- Ensure line number dot is hidden in Safari desktop, and all mobile browsers (in addition to desktop Chrome and Firefox)
- Ensure line number dot is hidden when both transcription and translation are shown and aligned, as well as when only one is visible/available

Fix Safari issues with line number dot cover (#1408)

---

sitemedia/scss/components/_transcription.scss

**Associated Issue(s):** https://github.com/Princeton-CDH/geniza/issues/1408#issuecomment-3275987683
Per https://github.com/Princeton-CDH/geniza/issues/1408#issuecomment-3275987683:
- Minor CSS change to ensure RTL line numbers are fully visible in Safari desktop

Handle RTL line numbers cut off in Safari (#1408)
